### ISSUE TITLE
How to upload an own MP3 Message?

### ISSUE THREAD

**Issue by HMNutzer** [Supergiovane/node-red-contrib-tts-ultimate#1]
Hello,

thank you for your pallette.
I hope youn can tell me, how to upload a amp3 file with a message to be said by the Sonos.
Your sample files work, but when I cose a file ti upload I can see for 1-2 seconds the filename next to the upoad button, but then the filename disappers.

Best wishes for X-Mas an thnks in advance

Martin

**Comment by Supergiovane** [comment]
Hello Martin
Do you run nodered behind docker, homeassistant, homematic or something similar?
If yes, you need to be sure that the user running nodered, has the right to wrote to the filesystem.

**Comment by HMNutzer** [comment]
Hello,

thank you for your fast response.
I'm running nodered on RaspberryMatic; installed an a virtual machine.
In which folder should the files be stored?
At the moment I found the workaround to copy the files in the folder "./ttspermanentfiles" with the prefix "OwnFile_".

Best regards

Martin

**Comment by Supergiovane** [comment]
Hi Martin
please allow full access to the .node-red/sonospollyttsstorage folder and subfolders. Thanks.

**Comment by HMNutzer** [comment]
Hi,
thank you for yout help.
Bye
