### ISSUE TITLE
CR: Clear Queue

### ISSUE THREAD

**Issue by Christchoper** [Supergiovane/node-red-contrib-tts-ultimate#10]
Hi Supergiovane
Thanks for your great Node and it works like a charm.

I have just on little thing that would be very nice. I use your Node for sending my own Files to Sonos in a Alert System. Now it would be a greate Feature when the node has a switch for clearing the queue.

I hope you can spend time for this Change.

I look forward,

Cheers,
Chris

**Comment by Supergiovane** [comment]
Hi Chris,
Thanks. 
You need a msg input to clear the current TTS queue being played from the node and to force the node to stop the current speak, is that correct?

**Comment by Christchoper** [comment]
yes, that would be exactly what I need.
Thanks in advance

**Comment by Supergiovane** [comment]
Hi Chris,
V. 1.0.13 is out with your request. Please see the README on how to use it.
Please star my node if you like it!
Thanks.

**Comment by Christchoper** [comment]
Hi Supergiovane,
Your extension of the node works perfectly.
I have only one question, is there a possibility to stop the node while it is playing something?
Thanks for your great support,

Chris

**Comment by Supergiovane** [comment]
Hi Chris
Yes, not now, but i'll add this in the next version.
In the meantime, you can send this to the node:
`// Stop
msg.payload="";
msg.priority = true;
msg.nohailing=true;
return msg;`

**Comment by Supergiovane** [comment]
Hi Chris
I've pushed out the V. 1.0.14 with` msg.stop = true` command.
You should see it as soon as node-red palette manager has updated the package.
