### ISSUE TITLE
TTS cache not found 

### ISSUE THREAD

**Issue by guenter-ms** [Supergiovane/node-red-contrib-tts-ultimate#11]
Hello!

And congratulations to this powerful and awful node!

I only have a question where to find the cache dir for the amazon aws speech files. I couldn't find.

And just for your information: If text input is too long (e.g. weather forecast), node red crashes, see attached. This prob can be solved easy by splitting the input with the "split" node, e.g. with period or comma as separator to split long text into multiple short texts. Works fine and could be a hint on your documentation.

Best
Guenni

![Bildschirmfoto 2021-01-29 um 15 15 28](https://user-images.githubusercontent.com/6253315/106285535-e7baa880-6244-11eb-8f9e-f92f1fcdf63d.jpg)

**Comment by Supergiovane** [comment]
Hi Guenter
Holy crap! I never tested it with such as long text!
I'll work on a FIX as soon as possible!
The cache folder is in the **.node-red/sonospollyttsstorage** folder.

**Comment by Supergiovane** [comment]
PS: can you try, please, with the google TTS engine, the engine without authentication.
It should work with it, because i already split the message if it's too long.

**Comment by guenter-ms** [comment]
Thank you,

I tried a simple flow with Hello World message (see below) to google tts engine. Hailing comes, but no speech. 

log shows: 
Jan 29 19:15:00 homematic-raspi daemon.info node-red[1554]: ttsultimate: Hailing .MP3, skip polly, filename: Hailing_ComputerCall.mp3

Whats my mistake?

[{"id":"d0167a74.9a91f8","type":"ttsultimate","z":"9b775466.ac28c8","name":"","voice":"de-DE","ssml":false,"sonosipaddress":"192.168.178.70","sonosvolume":"20","sonoshailing":"Hailing_ComputerCall.mp3","config":"557d8082.eb5a8","property":"payload","propertyType":{},"rules":[],"x":498.19862365722656,"y":508.7754430770874,"wires":[[],[]]},{"id":"6cdd8174.7daeb","type":"inject","z":"9b775466.ac28c8","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"Hello world, good evening","payloadType":"str","x":275.0142364501953,"y":509.0056571960449,"wires":[["d0167a74.9a91f8"]]},{"id":"557d8082.eb5a8","type":"ttsultimate-config","name":"googletranslate","noderedipaddress":"192.168.178.81","noderedport":"1984","purgediratrestart":"leave","ttsservice":"googletranslate"}]

**Comment by Supergiovane** [comment]
Ip and port you’ve set, are right?

**Comment by guenter-ms** [comment]
yes, double-checked 3 times :-( 
AWS works fine

**Comment by Supergiovane** [comment]
Ok let me work on that. I’ll let you know.

**Comment by Supergiovane** [comment]
Hi Guenter
the **issue is in the free google translate engine**. It's down since 2 days, for a unknown reason.
Anyway, V. 1.0.15 is out with payload splitting.
Please let me know if it works now with AWS.

**Comment by Supergiovane** [comment]
Hi again
1.0.16 has fixed the google translate engine as well.

**Comment by guenter-ms** [comment]
Hi supergiovane,

here is my feedback:

1. I could download now v15 (there is a time gap until a new version is available)

2. message splitting works fine, BUT at the split point you will hear an unnatural pause in a spoken sentence. I guess you are looking for the last possible word in a string, separated by a blank. I used .,:! as separators in a 4-split-node sequence. Then it sounds perfect. Maybe you add this as a configurable option (separators) and let the blank as a last mechanism to avoid the overflow.

3. the msg.stop=true doesn’t work. Node shows „notifyError: undefined (30, 3:27:28 PM)“. Its a good feature which I appreciate.

4. I have build a very funny alarm clock, where every 5 minutes different speeches appear: time, outside temperature, its raining (if it does), from internet: weather forecast, joke of the day, zitat of the day, becoming louder and louder….. Its really funny. So immediately stopping speeches when hitting the „Alarm stop“, is very good!

5. with migration from sonospollytts all user defined hailing mp3’s get lost. just for info.

Take care!
Guenter      





Am 30.01.2021 um 15:11 schrieb Supergiovane <notifications@github.com>:


Hi again
1.0.16 has fixed the google translate engine as well.

**Comment by Supergiovane** [comment]
Hi
The 5. Is very strange, because tts ultimate uses the exact same folders. I’ll take a look at all.

**Comment by guenter-ms** [comment]
Hi,

got v16 now.

google translate works fine!

stop is working (no error), if you add any payload like this (but payload is not spoken):

// Stop whatever is playing
msg.stop = true;
msg.payload = „abc";
return msg;

Am 30.01.2021 um 16:19 schrieb Supergiovane <notifications@github.com>:


Hi
The 5. Is very strange, because tts ultimate uses the exact same folders. I’ll take a look at all.

**Comment by Supergiovane** [comment]
V. 1.0.18 is out.
This should cover all you need.
Splitting is a very time consuming task.

**Comment by guenter-ms** [comment]
Hi supergiovane!

You should immediately change your name to PERFECTgiovane!

Everything is fine, thank you for very good work,

Stay healthy
Guenter 



Am 30.01.2021 um 19:25 schrieb Supergiovane <notifications@github.com>:


V. 1.0.18 is out.
This should cover all you need.
Splitting is a very time consuming task.
