### ISSUE TITLE
Feature request: Polly Neural TTS support

### ISSUE THREAD

**Issue by mirague** [Supergiovane/node-red-contrib-tts-ultimate#14]
First of all: Great work on making it incredibly easy to get started and broadcast TTS on the Sonos system, well done!

Would it be possible to allow for using [Polly's neural TTS](https://docs.aws.amazon.com/polly/latest/dg/NTTS-main.html)? It sounds a lot more natural and would love to use that instead.

**Comment by Supergiovane** [comment]
I’ll take a look!

**Comment by Supergiovane** [comment]
Hi Mirague
as far as i can see, the neural engine support is very currently limited. My region doens't have any neural voice, so i cannot do any testing on that.
I'll wait for Amazon to release at least one voice from my region.

**Comment by mirague** [comment]
Alright, thanks for taking a look!
