### ISSUE TITLE
Config node not working

### ISSUE THREAD

**Issue by pvgent1** [Supergiovane/node-red-contrib-tts-ultimate#15]
Placed TTS-Ultimate node on flow, double clicked, in config it says add new config, clicked pencil, clicked add. clicked done. In config field i see config, did full deploy. When i try to edit the config, i get the message please save, full deploy. I can't edit the config. What am i doing wrong?

**Comment by Supergiovane** [comment]
Have you tried to restart nr?
Where is installed nodered?
Please at least say “Hello” whenever you need help.

**Comment by pvgent1** [comment]
Hello, My fault, didn't check the debug window Node.js v10.0.0 is a minimum requirement.

**Comment by Supergiovane** [comment]
Ok, please update and let me know.

**Comment by pvgent1** [comment]
Hello again.
Did an upgrade of NodeRed (including Node.js), everything is working fine now. Typical RTFM.
