### ISSUE TITLE
Interruptions during playback

### ISSUE THREAD

**Issue by mschoenel** [Supergiovane/node-red-contrib-tts-ultimate#16]
Since version 1.0.18 it often happens that the spoken text in Amazon Polly is no longer spoken fluently. Longer pauses can be heard during the voice output. Is this possibly due to the new split function?

**Comment by Supergiovane** [comment]
Hello,
yes. If the text is more than 190 chars long, it's splitted. Shorter texts are not affected in any way.

**Comment by mschoenel** [comment]
OK, thanks, but with Amazon Polly there were no problems with texts longer than 190 characters in the past, right? At least not with me. Now the voice output sounds very bad unfortunately.....

**Comment by Supergiovane** [comment]
Hi 
yes there is a problem, an old problem.
The node saves the filename on disk and there is a maximum filename lenght.
On wich system are you running nodered?

**Comment by mschoenel** [comment]
Nodered runs on a CCU3

**Comment by Supergiovane** [comment]
Ok, the filename lenght's  limit is 255 chars.
I can increase a little bit the current 190 chars.
Wich is the maximum lenght of the longer of your messages?

**Comment by mschoenel** [comment]
The length is between 50 and 260 characters

**Comment by Supergiovane** [comment]
Ok, in the next version, i'll try to increase the chars number to about 220 (i must leave some free chars, because there is a certain amount of tolerance in the splitting process).

**Comment by mschoenel** [comment]
Thanks, I hope this will help ;-)

**Comment by Supergiovane** [comment]
V. 1.0.19 is out with a slightly increased limit.

**Comment by mschoenel** [comment]
Thank you, I'll try this....

**Comment by mschoenel** [comment]
It works much better since your changes. Thank you very much!

**Comment by Supergiovane** [comment]
Good. Thank you to you and remember to star my node. :-)

**Comment by mschoenel** [comment]
Done => Star ;-)
