### ISSUE TITLE
Can't get Amazon Polly to connect

### ISSUE THREAD

**Issue by goldriver2** [Supergiovane/node-red-contrib-tts-ultimate#17]
Hi, first, thanks for this node,

I was using the sonospolly node and I am trying to migrate to this new node but I can't get the node to connect to Amazon Polly.

I enterted my key in the "AWS Access Key" filed, and my secret key in the "AWS Secret Key, when I hit Update, after about 10 seconds I have the following message in the "Voice field" : Error retrieving voices. Credentials errors, missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1

I am running version 12.8.6 of node.js.
I have deployed and restarted node-red but always the same error

Any hints on what I might be doing wrong ?

thanks for the help

![amazon_polly](https://user-images.githubusercontent.com/7215561/109432437-32ad1480-79d9-11eb-8c5b-d934d87a2624.JPG)

**Comment by Supergiovane** [comment]
Hello
Have you tried to restart nodered?
Please double check the credentials for blank spaces.
Also, if you comes from sonospollytts, you may need to recreate a new credential.

**Comment by Supergiovane** [comment]
PS: also please see this. https://github.com/Supergiovane/node-red-contrib-tts-ultimate/issues/12#issuecomment-774685833

**Comment by goldriver2** [comment]
I have been able to fix the problem by doing the following:

1- Deleted all tts config nodes
2- Restarted Node-red
3- Recreated a config node for the Amazon Polly
4- Saved the config 
5- Deploy
6- Retart Node-Red
7- Returned in the config node, entered the Key and secret code
8- Save
9- Deploy
10- Restart Node-Red

only then the error message dissapeared
