### ISSUE TITLE
No voices to select with amazon polly

### ISSUE THREAD

**Issue by MacPurschi** [Supergiovane/node-red-contrib-tts-ultimate#18]
Hi there, 
with Amazon Polly for me there are no voices to select.
<img width="891" alt="Greenshot 2021-03-06 19 54 38" src="https://user-images.githubusercontent.com/57176583/110217750-2122ab80-7eb6-11eb-80c3-81080226cf99.png">
I have no config file only access key and secret key.

**Comment by Supergiovane** [comment]
Hi Mac,
sorry for the late response, but gitHub failed to send me the notification email..
Please double check you credentials for spelling and blank spaces.
If you comes from sonospollytts, try to recreate a new aws credential password.
Thanks

**Comment by MacPurschi** [comment]
Hi Giovane,
I've checked your hints:

1. Restart node-red
2. create new access key for aws
3. put them via copy&paste into tts-ultimate config

But still same error message.

**Comment by Supergiovane** [comment]
Hi
please see here https://github.com/Supergiovane/node-red-contrib-tts-ultimate/issues/17#issuecomment-788033656
Do you had the old sonospollytts installed?

**Comment by MacPurschi** [comment]
Yes, I have the old sonospollytts installed, too, cause I'm not able to delete it.

**Comment by Supergiovane** [comment]
You need to delete all nodes in your flows, and then remove the sonospollytts config node.
To access the config nodes, click on the right menu on node-red

<img width="472" alt="Node-RED___192_168_1_16" src="https://user-images.githubusercontent.com/37666636/110343199-87313f00-802c-11eb-8516-9b74e86a35a8.png">

**Comment by MacPurschi** [comment]
Using this workaround works for me:

> #17 (comment)
