### ISSUE TITLE
Resume issue for TV input and paused queue

### ISSUE THREAD

**Issue by GHRRGH** [Supergiovane/node-red-contrib-tts-ultimate#2]
The palette works great when music is playing, however there are two scenarios where the action doesn't recover well:

1. TV input
When the Sonos speaker is using the tv input (either through HDMI ARC or line in), this is not resumed when the message has played. In this case, the last played playlist resumes, ignoring the TV input.

2. Paused queue (no media playing, but playlist is paused)
When the Sonos speaker is currently not in use, but a playlist is paused, this is not restored when the message has played. In this case, the message mp3 becomes the current playlist. When trying to resume the original playlist, it plays back the message again.

Thanks for this palette. Extremely useful and a great solution!

**Comment by Supergiovane** [comment]
Hi Gh
1. Unfortunately, i have no Sonos hardware for trying the tv input. Maybe in the future, i can give it a try
2. Will check it ASAP

**Comment by GHRRGH** [comment]
Great, thanks!

For the TV input, not sure if it helps, but when the TV input is active, the below attributes are indicating that (taken from Home Assistant Developer Tools):
media_title: TV
source: TV

**Comment by Supergiovane** [comment]
Ok, thank you.
I'll work on that infos.

**Comment by Supergiovane** [comment]
Hi Gh,
i need exactly to know, how an object is populated while listening of TV input.
Can you please copy the content of this zip, paste it into your **.node-red/node_modules/node-red-contrib-tts-ultimate/ttsultimate** folder and restart node-red?

Then, please try to:
Switch sonos to TV input and start playing something.
While playing, send a message to TTSUltimate as usual.
Copy and paste here the debug row starting with "BANANA GHRRGH" (you can either see the debug message in the node-red debug window on the right, or in the log console. The row interesting me starts with "BANANA GHRRGH")
Thanks.

[ttsultimate.js.zip](https://github.com/Supergiovane/node-red-contrib-tts-ultimate/files/5749857/ttsultimate.js.zip)

**Comment by GHRRGH** [comment]
Hello @Supergiovane 

I assume you meant line 201?
{"position":null,"duration":null,"queuePosition":1,"uri":"x-sonos-htastream:RINCON_xxxxxxxxxxxx01400:spdif"}
where xxxxxxxxxxxx is the device MAC address.

Some additional info on this scenario. The node does give an error when trying to resume. "upnp 500 (UPnP Error 711)"
It does however still resume the music queue instead of reactivating the tv input.

**Comment by Supergiovane** [comment]
Hi Gh
you should see something like this:

```
{
  id: null,
  parentID: null,
  title: 'tts.mp3?f=/home/pi/.node-red/sonospollyttsstorage/ttsfiles/Radar_stop_ taverna_stop_ Sud_stop__Bianca.mp3',
  artist: null,
  album: null,
  albumArtURI: null,
  position: 0,
  duration: 0,
  albumArtURL: null,
  uri: 'http://192.168.1.16:1980/tts/tts.mp3?f=%2Fhome%2Fpi%2F.node-red%2Fsonospollyttsstorage%2Fttsfiles%2FRadar_stop_%20taverna_stop_%20Sud_stop__Bianca.mp3',
  queuePosition: 1
}
```

**Comment by GHRRGH** [comment]
Yes, that's this one right: 
{"position":null,"duration":null,"queuePosition":1,"uri":"x-sonos-htastream:RINCON_xxxxxxxxxxxx01400:spdif"}

From the logger on line 201

**Comment by Supergiovane** [comment]
Ok, thanks, the "spdif" and the lack of "title" property is what i looking for.

**Comment by Supergiovane** [comment]
Hi Gh
V. 1.0.6 is out. Try it.
Please remember, that all APIs we use, are undocumented, so we need to go step by step and try.
This is a very time consuming job!!

**Comment by GHRRGH** [comment]
Hello @Supergiovane,

Thanks! Please find below the test results:

TV input: Works correctly now (and quite fast). Input is resumed immediately after the message is played

Regular playlist: This doesn't work anymore. The message is played, Node-Red displays "Done resuming music", but the music doesn't resume and the active (paused) media is the message that last played.

Sonos Radio: This works partly. The music is resumed, but the song title, album art, ... are missing.

**Comment by GHRRGH** [comment]
Paused queue: same behavior as before, identical to the "regular playlist" result now.

**Comment by Supergiovane** [comment]
Hi Gh
Ok, about the sonos Radio, i cannot do more than that, because i haven't any clue to fully control the radio. I can only send a uri stream for that. So sorry.
About regular playlist's queue, i tested mine and it works.I try again...

**Comment by GHRRGH** [comment]
In my case it's a queue from Spotify. I could provide you with the logger output again if that helps ?

**Comment by Supergiovane** [comment]
Is your playlist a native sonos playlist? Is made of mp3 you have on your disk?

**Comment by Supergiovane** [comment]
I tested a queue from Apple music, without any problem. Can you do the same as usual , and post me the result of the track object you see in the console window?
[ttsultimate.js.zip](https://github.com/Supergiovane/node-red-contrib-tts-ultimate/files/5754191/ttsultimate.js.zip)
with the attached file?

**Comment by Supergiovane** [comment]
Hi GH
then, try this.
[ttsultimate.js.zip](https://github.com/Supergiovane/node-red-contrib-tts-ultimate/files/5754269/ttsultimate.js.zip)

**Comment by Supergiovane** [comment]
V. 1.0.7 is out, should have fixed some things, but as i told you, more than that, i cannot do due to the lack of documentation. It seems that there's many type of radio stations: radios in stream, radios with embedded playlist, list of files, etc.. and the sonos api don't tell me which type of things i'm playing. Other than that, the sonos API cannot neither play a playlist via it's ID, nor a radio via it's ID.
More than that, i cannot do.
You should consider integrating TTS-Ultimate with sonos-plus node, that seems to be focused more on handling music. You can link TTS-Ultimate output to Sonos-Plus input to start the last radio station as you want.
TTS-Ultimate is more focused on TTS.

**Comment by GHRRGH** [comment]
Hello @Supergiovane,

Thanks! 1.0.7 covers all my needs (I don't really use Sonos radio).
And indeed I use Sonos-Plus for more advanced Sonos-specific features.

Results from my tests:
TV input: Still works correctly
Regular playlist: Works again
Paused queue: Works as well now

Sonos Radio: This still had an issue. In my tests, the music was resumed correctly (same behavior as mentioned above though). However, 1 second later, it turns off the radio and goes back to the previously used queue (paused).
