### ISSUE TITLE
Running in docker

### ISSUE THREAD

**Issue by thalch** [Supergiovane/node-red-contrib-tts-ultimate#21]
Hi,

I have node red running in a docker container and want to use your TTS ultimate solution for some massages triggered by events. Somehow I do not get the sound to the speaker. I have fixed ip addresses for the Sonos devices as well as for the Raspberry running docker. The status  in node red is „connected“ but when I run your demo flow with „hello world“ I hear nothing. Sonos playing music is interrupted. I‘m using google without authentication. Seems the sound file is not available. Do you have any Tipps what I can do? Where should I find the sound files?

Thanks for some insights
Chris

**Comment by Supergiovane** [comment]
Hi running docker on a rpi is always problematic.  
Check the port forwarding by looking at the Readme page on github. 
Then check whether the user running node-red has rights to write to the filesystem.
