### ISSUE TITLE
Error playing

### ISSUE THREAD

**Issue by McFozzy75** [Supergiovane/node-red-contrib-tts-ultimate#22]
I have made an setup. It found the sonos. The status is recieved. But when I want to play (tts or mp3)  an error is shown in the Sonos app:
_Can't 'tts.mp3?f\........' play. The track isn't coded correctly_. (Error translated from dutch to english)

I hope you can help

**Comment by Supergiovane** [comment]
Hi
What are you using? Raspberry with nodered, docker or what?

**Comment by McFozzy75** [comment]
Windows 10 with nodered

**Comment by McFozzy75** [comment]
`[{"id":"39fb8d64.36ef92","type":"ttsultimate","z":"cceef318.9c664","name":"","voice":"en-GB","ssml":false,"sonosipaddress":"192.168.0.133","sonosvolume":"50","sonoshailing":"0","config":"725b399d.49b168","property":"payload","propertyType":{},"rules":[],"x":340,"y":660,"wires":[["12316c96.37ad73"],["c4cbd293.00333"]]},{"id":"954d5d45.f07a6","type":"inject","z":"cceef318.9c664","name":"","props":[],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":130,"y":580,"wires":[["60ff1779.6288e8"]]},{"id":"12316c96.37ad73","type":"debug","z":"cceef318.9c664","name":"Status","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":540,"y":640,"wires":[]},{"id":"60ff1779.6288e8","type":"function","z":"cceef318.9c664","name":"","func":"// Play a message\nmsg.payload = \"Hello, the current temperature is 12°\";\nreturn msg;","outputs":1,"noerr":0,"initialize":"","finalize":"","x":180,"y":660,"wires":[["39fb8d64.36ef92"]]},{"id":"c4cbd293.00333","type":"debug","z":"cceef318.9c664","name":"Error","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","statusVal":"","statusType":"auto","x":550,"y":700,"wires":[]},{"id":"725b399d.49b168","type":"ttsultimate-config","name":"Sonos","noderedipaddress":"192.168.0.143","noderedport":"1980","purgediratrestart":"purge","ttsservice":"googletranslate"}]`

**Comment by Supergiovane** [comment]
Please check that the windows firewall is accepting incoming connection from port 1400. 
You can try to temporary disable the firewall as well. 
Try also to use the ownfile node. This avoid the download the mo3 voice text from the tts service. 
See the examples on the github page.

**Comment by Supergiovane** [comment]
PS: also please see this web page: https://technikkram.net/blog/2020/09/26/sonos-sprachausgabe-mit-raspberry-pi-node-red-und-amazon-polly-fuer-homematic-oder-knx-systeme

It mentions sonospollytts, but now sonospollytts has been renamed in tts-ultimate.

**Comment by McFozzy75** [comment]
Port 1400 and 1980 are open in the Firewall. Even with OwnFile I get the same Error. The (tts.mp3) files that are genarated are only 14 bytes in size

**Comment by McFozzy75** [comment]
the tts.mp3 contains "File not found" if i open it in Notepad++

**Comment by Supergiovane** [comment]
Hi
Please check wether nodered does have full access to these folders. It’s very strange. Have you tried to restart nodered?

**Comment by McFozzy75** [comment]
Hi,

Yes I rebooted the system. And NodeRed has got access to these folders. If I create an http-node with a link to the local folder (C:\Users\mjans\.node-red\sonospollyttsstorage\ttspermanentfiles\OwnFile_Porta aperta.mp3) it works fine. 

http://192.168.0.143:1880/Voice plays the file from the browser.

Is tts.mp3 stored in a local cache folder? 

`[{"id":"70391a4e.903dd4","type":"http in","z":"cceef318.9c664","name":"/Voice","url":"/Voice","method":"get","upload":false,"swaggerDoc":"","x":810,"y":380,"wires":[["2d7c0593.94661a"]]},{"id":"2d7c0593.94661a","type":"file in","z":"cceef318.9c664","name":"OwnFile_Porta aperta.mp3","filename":"C:\\Users\\mjans\\.node-red\\sonospollyttsstorage\\ttspermanentfiles\\OwnFile_Porta aperta.mp3","format":"","chunk":false,"sendError":false,"encoding":"none","x":1020,"y":380,"wires":[["282c26eb.aa030a","83acf50e.75fca8"]]},{"id":"282c26eb.aa030a","type":"http response","z":"cceef318.9c664","name":"","statusCode":"","headers":{"content-type":"audio/mpeg"},"x":1270,"y":380,"wires":[]},{"id":"83acf50e.75fca8","type":"debug","z":"cceef318.9c664","name":"","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1280,"y":440,"wires":[]}]`

**Comment by Supergiovane** [comment]
No, tts.mp3 is only an endpoint that streams the actual file requested by the querystring f=….
The webserver node does work because you’re downloading a file using the nodered webserver on the port 1880. 
Please be sure to have node v.14 or above and nodered 1.x or above. 
To see the node version, type node -v in a prompt window.

**Comment by McFozzy75** [comment]
The versions are OK:
node v.14.16.0
nodered V1.2.9.

Below the error from Sonos and my config screen.

![Screenshot_20210505-223042_Sonos](https://user-images.githubusercontent.com/83723167/117206050-a6610880-adf2-11eb-933a-bbc431bdc43c.jpg)

![image](https://user-images.githubusercontent.com/83723167/117206199-d90b0100-adf2-11eb-805c-d8e7a1830eb0.png)

**Comment by Supergiovane** [comment]
Hmmm it seems there is a problem with your file path 
Tomorrow, once in office, i’ll take a look closer!

**Comment by Supergiovane** [comment]
Hi Mc
i've been able to reproduce your issue.
I've tried on linux and all went fine, but with windows i get exactly your error message.
Please stay tuned as a fix will be out in about 2 hours.

**Comment by Supergiovane** [comment]
Hi Mc
v. 1.0.20 is out with the fix.
Hope you enjoy tts-utlimate.
Thanks!
If you still have trouble, please reopen this issue.
