### ISSUE TITLE
Error migrating from Polly node

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [Supergiovane/node-red-contrib-tts-ultimate#24]
I just changed my flows to use the new ultimate-node instead of Polly-tts.

The node does work with "Google without authentication" but I do not like the voices and would prefer the AWS ones

My AWS credentials were working fine with Polly-tst. However, im getting below error messages when using AWS credentials in the ultimate node
`"ttsultimate-config: Error getting polly voices CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1"`

Please advise on where I have to update this in my setting. 
I'm running the latest Node-Red in Ubuntu-Docker.

thanks for your help

**Comment by Supergiovane** [comment]
Hi
You probably need to change your credential key in AWS.
Sometime, reused credential keys for other service endpoint are not allowed.
Please also uninstall sonospollytts.

**Comment by xX-Nexus-Xx** [comment]
Thanks for the quick response.
sonospollytts is already uninstalled and I will get new credentials now

**Comment by xX-Nexus-Xx** [comment]
Sorry, I just generated new credentials but the error remains the same

`"ttsultimate-config: Error getting polly voices CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1"`

![image](https://user-images.githubusercontent.com/2195190/118763424-3014d980-b8bb-11eb-94ca-d6817fe1f3c7.png)

**Comment by Supergiovane** [comment]
Hi
have you changed the credentials in the config node as well, richt?
Have you restarted nodered?

**Comment by xX-Nexus-Xx** [comment]
OK, it looks like it took a while to sync. I did restart Node-Red 3 times and it is working now

thx a lot .. all good !
