### ISSUE TITLE
[question]  Overwrite Main-Sonos-Player via Input Parameter

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [Supergiovane/node-red-contrib-tts-ultimate#28]
Hi, Is it possible to overwrite the target sonos (Main-Sonos-Player) with and overwrited via input (like you do it with msg.volume)

Example:  msg.player = "Bedroom" or msg.player ="Group: House"

thanks for considering

**Comment by Supergiovane** [comment]
Hi Nexus
I’ll take a look. 
Currently, you can use 1 node each room and use the nodered link-in and link-out nodes to point to each one.

**Comment by Supergiovane** [comment]
Hi Nexus
Have you seen the readme?
I thing this is what you need:

setMainPlayerIP
Sets the main player IP. This will also be the coordinator if you have a group of players

setPlayerGroupArray
Sets the array of players beloging to the group, if any.
If you have only one additional player, you need to ever put it into an array. See below.

// Set player IP
var config= {
    setMainPlayerIP:"192.168.1.109"
};
msg.setConfig = config;
return msg;
// Set player IP and additional players
var config= {
    setMainPlayerIP:"192.168.1.109",
    setPlayerGroupArray:[
        "192.168.1.110",
        "192.168.1.111",
        "192.168.1.112"
    ]
};
msg.setConfig = config;
return msg;
// If you have only one additional player
var config= {
    setMainPlayerIP:"192.168.1.109",
    setPlayerGroupArray:["192.168.1.110"]
};
msg.setConfig = config;
return msg;

**Comment by xX-Nexus-Xx** [comment]
Yes, I was playing with that option .. but somehow I'm unable to get it working :(

current scenario
- TTS Node is set to 192.168.2.226 (default for all messages ... is working fine!)
- Overwriting via input  msg.setMainPlayerIP = 192.168.2.226 and send it to TTS Node (no other change) .. does not work
- no groups are defined

any suggestions? ... Ideally I would like to use the PlayerName (e.g.Bedroom) and not the IP ..but I can work with that ;)

**Comment by Supergiovane** [comment]
Hi
you need to pass an object, you cannot simply pass a msg.setMainPlayerIP command.
Please see the README and copy exactly what you see.

<img width="595" alt="Supergiovane_node-red-contrib-tts-ultimate" src="https://user-images.githubusercontent.com/37666636/124432850-5d85eb80-dd72-11eb-9cec-69353f4680da.png">
