### ISSUE TITLE
Sonos Discovery fails when Node-Red and TTS-Ultimate are on different networks

### ISSUE THREAD

**Issue by pshellguruwannabe** [Supergiovane/node-red-contrib-tts-ultimate#30]
I recently moved my sonos speakers to a separate network. I added a second nic on my node red server that is connected to that network. However, TTS-Ultimate will not discover them.  I can input an IP address of one of the speakers and it works fine that way, but i can't use multiple speakers now.

**Comment by Supergiovane** [comment]
Hi,
multi interface is not supported, sorry!
If you wish, you can add this function and raise pull request. You're wellcome!

**Comment by pshellguruwannabe** [comment]
Just a side note, i had to reboot the vm i have this running on, and it magically started working....

**Comment by Supergiovane** [comment]
Perfect!
