### ISSUE TITLE
Skipping to next track

### ISSUE THREAD

**Issue by jabberwock95** [Supergiovane/node-red-contrib-tts-ultimate#31]
Hi,

Running node-red in home assistant, when I use this node on a Sonos playing a playlist from Spotify, the Sonos will start playing the next track in the queue after speaking the message, rather than pausing and resuming the current track. 

I can get around the issue somewhat by sending a pause command before running the TTS node and then a resume command afterwards.

**Comment by Supergiovane** [comment]
Hello
Yes, resuming app queues isn’t reliable. It’s an issue i cannot overcome.
