### ISSUE TITLE
delay before TTS

### ISSUE THREAD

**Issue by tinimark** [Supergiovane/node-red-contrib-tts-ultimate#32]
Love this node, working fine for me except when it interrupts music you can hear the volume change on the current playlist just before it reads the message. Also there seems to be quite a delay from when the msg is sent to when it is being played. It's about 8 seconds or so. Anything I can do from my end to speed that up?

**Comment by Supergiovane** [comment]
Hi
8 seconds are way too much. Normally, it takes about 1 or 2 seconds to start playing. 
There is something wrong. 
On what hardware are you running nodered?
Do you play everytime the same text, or it changes?

**Comment by tinimark** [comment]
Thanks for the quick reply.
Running Hassos on a dedicated i5 box. Everything else working fine.
I can send a TTS using the HA sonos card and it plays instantly but of course doesn't revert back to the queue after playing.
I'm playing the same message each time.

**Comment by Supergiovane** [comment]
I’ve understood. Nodered is running behind homeassistant. 
Please check that the port used by tts-ultimate are open. 
Running nodes behind homeassistant, docker or something like this, requires port forwarding

**Comment by tinimark** [comment]
ah that's great I'll check that out and let you know. Thank you! :)

**Comment by Supergiovane** [comment]
PS: please try to use an ownfile node to play one of the demo texts. In this case, trs ultimate will not contact the tts online service to download the mo3 of the tts file. 
Let me know if it’s more speedy.

**Comment by tinimark** [comment]
Brilliant. I'll give it a go!

**Comment by Supergiovane** [comment]
Hi tinimark,
are you skilled enough to replace a file into your .node-red folder?

**Comment by tinimark** [comment]
Good morning!
Yes, I have access to \\HASSIO\config\node-red
Port forwarding didn't seem to improve anything but I may well have done that wrong.

![image](https://user-images.githubusercontent.com/12912074/130569927-8ef542aa-7303-4066-9c86-65a84488e9d3.png)

**Comment by Supergiovane** [comment]
Hello
ok, so please unzip this zip into your **.node-red/node_modules/node-red-contrib-tts-ultimate/ttsultimate** folder and restart nodered.
[ttsultimate.js.zip](https://github.com/Supergiovane/node-red-contrib-tts-ultimate/files/7037046/ttsultimate.js.zip)

This should fix the first issue about playlist volume. Please try it and let me know.
Next step, will investigate the 8 seconds issue.

**Comment by tinimark** [comment]
Yes, brilliant, that worked for the volume issue :)
The delay is about 8 to 10 seconds to play the file and then about another 8 to 10 seconds for the queue to resume.

**Comment by tinimark** [comment]
this might help?
![image](https://user-images.githubusercontent.com/12912074/130573451-0b143358-c273-40fc-a59d-0ce145ff323a.png)

**Comment by Supergiovane** [comment]
Hi
yes. That is.
Have you added some additional players in the config window?

**Comment by Supergiovane** [comment]
I mean here:

<img width="548" alt="Node-RED" src="https://user-images.githubusercontent.com/37666636/130574094-180acbf9-7ca1-4fe7-b968-73c6cc921182.png">

**Comment by tinimark** [comment]
No, I only have one Sonos device.

**Comment by Supergiovane** [comment]
Hi
can you send me the same screenshot i sent you? I need to view if there's an empty row.

**Comment by tinimark** [comment]
That was it! 
There was an empty node in additional players. I deleted it and the delay has gone.
Amazing work, Max.
Grazie and have a great day.

**Comment by Supergiovane** [comment]
Prefect.
I'll publish the official updated release tomorrow.
In the meantime, you can live with the fix i sent you.
Cheers and... please star my node.
