### ISSUE TITLE
Resume issue with empty playlist

### ISSUE THREAD

**Issue by shbert** [Supergiovane/node-red-contrib-tts-ultimate#33]
Hi,

thanks for the great plugin and continuation of the work, I just switched in one  of my installations from sonospollytts to here.

** Issue **
When my playlist is empty, somehow the TTS track played (ownfile and normal) gets added to the playlist, or is at least set as the last song played in sonos. So I get some weird echo effect, when playing a second time, or it repeats the original message, when playing a new message right after the first one.

With one song in the playlist this behavior is gone.

Is it possible to handle this "empty playlist" issue, with removing all items from sonos, before playing, e.g. the next tts?

I'm still on sonos version 1. Wether this is causing the issue I can not verify.

**Comment by Supergiovane** [comment]
Hi
It’s very strange, because sonos shouldn’t add the tts to the playlist. 
if the playlist is empty, tts-ultimate will skip resuming it. 
I’m on sonos v2. 
Leave me some time to get my old v1 and to test it.

**Comment by Supergiovane** [comment]
Ok, i'm able to reproduce the issue.
I'm working on that. 
A Fix should be out in about 2 hours.
I'll keep you advised...

**Comment by Supergiovane** [comment]
Hi,
node-red-contrib-tts-ultimate@1.0.26 is out with that fix.
Please try it as soon as you see it in the palette and remember to star my node if you find it useful.
Thanks

**Comment by shbert** [comment]
Thanks for the quick fix, tested and works now as expected.

**Comment by Supergiovane** [comment]
Thank you!
