### ISSUE TITLE
TTS-Error in debug - Node works fine

### ISSUE THREAD

**Issue by xX-Nexus-Xx** [Supergiovane/node-red-contrib-tts-ultimate#34]
Hi, during the testing with my previous issue I found some debug error messages which occur every time I generate a TTS either via new next or via an existing mp3 file.

The below error messages appear with each TTS announcement. Everything is working fine, despite the below messages. 

I can see this error message in the Node-Red Debug-UI.

1st Error:
`"ttsultimate: Error STOPSync: upnp: statusCode 500 & upnpErrorCode <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>701</errorCode></UPnPError></detail></s:Fault></s:Body></s:Envelope>"`

2nd Error:
`"ttsultimate: Error stopping in HandleSend: upnp: statusCode 500 & upnpErrorCode <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>701</errorCode></UPnPError></detail></s:Fault></s:Body></s:Envelope>"`

3rd Error:
`"ttsultimate: Error SEEKSync: upnp: statusCode 500 & upnpErrorCode <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>701</errorCode></UPnPError></detail></s:Fault></s:Body></s:Envelope>"`

My docker-log for Node_red is showing the the above error message as well (here an example):

`29 Aug 11:56:59 - [error] ttsultimate: Error SEEKSync: upnp: statusCode 500 & upnpErrorCode <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>701</errorCode></UPnPError></detail></s:Fault></s:Body></s:Envelope>`

As mentioned above, everything works fine but these messages appear

======
I'm using node-red-contrib-tts-ultimate 1.0.24 (+latest JS file you sent me) on Ubuntu Docker Node-Red V2.0.1
I have a Sonos-Beam at the TV (this is where I checked for the issues) additionally I have 2xSonos5 and several Sonos1
I'm using the Amazon-Polly TTS (with the default Joanna voice) no other players are defined in the config

**Comment by Supergiovane** [comment]
Hi
tts-ultimate is trying to resume the previous queue, but some queues doesn’t support some commands. 
Sonos API is a closed source code, so the entire code you see on github is a reverse engineered one. I’ll hide these annoying messages in the next version. In the meantime, simply don’t care :-)

**Comment by xX-Nexus-Xx** [comment]
what I thought as well ;) thats why I mentioned that it is working

thanks for your great support
