### ISSUE TITLE
not an issue, but still a question

### ISSUE THREAD

**Issue by NikAWing** [Supergiovane/node-red-contrib-tts-ultimate#37]
Hello! :)

Is it possible to make a branch that does not need a Sonos speaker, but plays the audio on a raspberry pi instead?
Beside physical audio outputs there also is BT on a raspberry pi.
And there are cheap BT receiver circuits available, it would be great to just play the audio over bluetooth.
Having the cache is great and all the features in this node, but it wants and looks for a Sonos speaker (and I also don't yet know why it needs a server/port open, maybe because of Sonos?).

I did not find anything similar to this node, there only is a wavenet node which needs a Google API key.
Also, the google website https://cloud.google.com/text-to-speech has a lot of voices, having this and bluetooth sound makes it very interesting :o

Best regards!
Nik

**Comment by Supergiovane** [comment]
Hi Nik
Branching/forking are wellcome. 
I have no knowledge on what you’re asking, but if you wish develop it, you’re wellcome!

**Comment by NikAWing** [comment]
Hey :)

Oh, so you did not code this node?
I basically ask if it is possible to have this node just without the Sonos part. Create/store a sound/audio file and play it on the raspberry that is running node red. I know it's possible to play audio files with node red, but there is no other node like this one with cache and also no need for google credentials etc.

I am not good enough to make a branch and alter it, I just try to find out if there is anything that comes close to what I'm looking for :D

**Comment by Supergiovane** [comment]
Hi
This is beyond the scope of this node. 
What i can try to do, is to disable tha sonos part and only save the file, but then you’ll need a way to read the file as soon as it has been saved and send it to the rpi speaker or bluetooth. 
I cannot unfortunately do it for you, because i haven’t any knowledge on how to do it.

**Comment by NikAWing** [comment]
Hello :)

I think this could work! :)
I don't have enough knowledge to alter the code, I only "speak" vb.net and Arduino IDE, lol
Basically it would end after creating the file. I don't know if it is possible to have some "output" after the file was created, this could trigger another node that plays the audio file on the raspberry.
Having the cache is a great idea, this way already existing files don't have to be created each time.

The port that needs to be open, is it for the Sonos speaker to work or is it for google services?

**Comment by Supergiovane** [comment]
Hi 
The port is for the sonos.  
I’ll take a look monday at hoffice.

**Comment by NikAWing** [comment]
Thanks a lot!
No need to hurry, I just think IF it works out, it might be an interesting solution not just for me :)

**Comment by Supergiovane** [comment]
Hi
v.1.0.29 is out in the palette menu in about 1 hour.
Please see the readme on github on how to set no players.

**Comment by NikAWing** [comment]
You're my hero!
Perfect and thanks a lot!
