### ISSUE TITLE
Sonos loses current music stream

### ISSUE THREAD

**Issue by jmorris644** [Supergiovane/node-red-contrib-tts-ultimate#4]
When I am listening to Pandora and I tell the node to play some content, my Sonos connect loses the current stream and starts to play what is in the queue.

**Comment by Supergiovane** [comment]
Hi Jmorris,
yes, the Sonos API are undocumented and it's nearly impossible to resume a radio station.
Sorry for that, but i'm unable to fix it at the moment.
