### ISSUE TITLE
can't get azure to work

### ISSUE THREAD

**Issue by dkrasmussen** [Supergiovane/node-red-contrib-tts-ultimate#41]
hi

first thanks for the quick including of azure tts

i dont know if there is a bug, but i can't get it to work

on deploying i got this warning:
"ttsultimate.config: Microsoft AzureTTS service disabled. throwIfNullOrUndefined:subscriptionKey" and yes i have pasted a key and westeurope

and when i try to play audio i got thes error:
"ttsultimate: node id: xxx Error Downloading TTS: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined. THE TTS SERVICE MAY BE DOWN."

i'am pretty sure i'am the problem :) but i hope for a little help

i got the key from "home > cognitive services" and then "Manage keys"

if thats not the correct place, then please point me in the right direction 

/DKR

**Comment by Supergiovane** [comment]
And please show me the screenshot of your config window.. i mean this:
<img width="533" alt="Node-RED" src="https://user-images.githubusercontent.com/37666636/137322241-cf164e8d-8ef5-4c48-a874-de24e37d2eb9.png">

Send the key to maxsupergiovane@icloud.com, thanks.

**Comment by dkrasmussen** [comment]
hi, 

as you can see there is no voices in the list, and i think it throw an error
<img width="824" alt="Skærmbillede 2021-10-14 kl  17 46 16" src="https://user-images.githubusercontent.com/22856920/137403828-24c113f7-1002-4000-a7b0-74d9d14d5634.png">

/DKR

**Comment by Supergiovane** [comment]
Hi DKR
Any news?
