### ISSUE TITLE
Play longer text

### ISSUE THREAD

**Issue by dkrasmussen** [Supergiovane/node-red-contrib-tts-ultimate#42]
Hi

Is there a way to play a longer text without splitting it ? 
using azure tts

/DKR

**Comment by dkrasmussen** [comment]
hi

maby something like a <input> in the tts node "split text after x char, 0=auto (type number)"

and in the code

if (splitTxt == 0) 
     use exsting code
else
    simple hard split after x char, if you want to bi nice, then split at last space :)
fi
  

/DKR

**Comment by Supergiovane** [comment]
A suitable way can be a setting to comoletely enable/disable split. 
Would be ok for you?

**Comment by Supergiovane** [comment]
node-red-contrib-tts-ultimate@1.0.36 is out with settable text lenght. See the README for that.
