### ISSUE TITLE
name resolving does not work

### ISSUE THREAD

**Issue by pvklink** [Supergiovane/node-red-contrib-tts-ultimate#44]
**Salutation (i'll not respond to users that doesn’t wrote at least "Hello")**

In ttsultimate as part of a node-red docker config on a rpi 4b
only the ipadres 192.168.20.48 works in the node as node-red-ip

when i use localhost or 127.0.0.1 or a host name is does not work!
I also restarted NR

**Expected behavior**
I like name resolution to work with or at  least 127.0.0.1 or localhost

**TTS-Ultimate Version**
i use NR 2.1.3

on a docker on a rpi with latest OS

**Comment by Supergiovane** [comment]
Where is the salutation?
You cannot use a loopback address. How can sonos know, where your NodeRed is if you use 127.0.0.1?
