### ISSUE TITLE
Red triangle showing next to node

### ISSUE THREAD

**Issue by dxdc** [Supergiovane/node-red-contrib-tts-ultimate#45]
![image](https://user-images.githubusercontent.com/7200365/140747763-33a84241-be18-4fa3-8768-dcff8c82baa4.png)

Recently updated to latest version. Had Google and AWS Polly set up previously, everything was working fine. Now I see the red triangle error that something is wrong in the config. I deleted the AWS Polly but still no change. I also see several warning messages in the debug pane.

**Comment by dxdc** [comment]
Thanks for the quick reply! The node didn't do it automatically for me (as far as 220), but I manually put it in and then the error went away.

**Comment by Supergiovane** [comment]
Hi
it dit it internally, if you leaves the field empty.
The nodes aren't allowed to manually insert anything in the HTML interface, but they are allowed to do it in the js code :-)
