### ISSUE TITLE
not playing mp3 file anymore from ownfile node

### ISSUE THREAD

**Issue by Vinisz** [Supergiovane/node-red-contrib-tts-ultimate#46]
Goodday, think I have an issue with the latest version, hope you can have a look... 

**Describe the bug**
I have an "ownfile" node in front with an mp3. Before, the mp3 file was playing fine, now, TTS ultimate just announces the word "mp3" to the sonos speakers

**To Reproduce**
1. Create flow with ownfile node in front
2. Upload mp3 file to ownnode
3. Try to play the mp3 via ownnode to ttsultimate
4. Sonos will just play the word "mp3"

**Expected behavior**
Play the MP3 file of the ownnode

**Screenshots**
![image](https://user-images.githubusercontent.com/49644964/140990814-ad1ff6dd-9963-4f28-a5d9-84aedf01e6c8.png)
![image](https://user-images.githubusercontent.com/49644964/140990857-33afac90-375c-4c39-ae49-0525f48b35f1.png)
![image](https://user-images.githubusercontent.com/49644964/140990966-c11ab483-6a52-41b0-ada9-cc1817cab95e.png)
![image](https://user-images.githubusercontent.com/49644964/140990997-9afb9948-e0b7-4a33-a932-43cfaf6a644c.png)

**TTS-Ultimate Version**
 - 1.0.36

**Are you running node-red behind homematic, docker or anything similar?**
 - Docker on Synology NAS

**Additional context**
Works fine in previous version (might be view versions back)

**Comment by Supergiovane** [comment]
Hi
I’ll take a look tomorrow. 
in the meantime, you can install a previous version. To do that, please see the npm web site.

**Comment by Vinisz** [comment]
Already found it... it has to do with "autosplit max length"
I configured it to "10" and that caused a mess... now on "100" , all good... 
![image](https://user-images.githubusercontent.com/49644964/140992807-30561bae-30c5-4a9a-b6c7-98d583e14c2c.png)
