### ISSUE TITLE
Doesn't play file from polly on Sonos

### ISSUE THREAD

**Issue by mbokor** [Supergiovane/node-red-contrib-tts-ultimate#47]
I have a raspberry matic running. In that raspberrymatic I installed the notered -plugin. I installed the tts-ultimate note and tried it with amazon polly. The requested mp3 - File is on the raspberry but the sonos says when i try to play it "Wiedergabe nicht möglich - Verbindung 172.0.0.1:1980 nicht möglich => it can't connect.

Can you please help me ?

Greetings Michael

**Comment by Supergiovane** [comment]
Hello Michael
What is your knowledge about networking?

**Comment by Supergiovane** [comment]
You must open the port and assure that the ip 172.0.0.1 is reachable from outside redmatic. Please ask how to do it, on raspberrymatic forum.

**Comment by mbokor** [comment]
Its Basic was ?

Von meinem iPad gesendet
