### ISSUE TITLE
TTS config warnings

### ISSUE THREAD

**Issue by plats98** [Supergiovane/node-red-contrib-tts-ultimate#49]
Hallo

I'm looking for a way to disable the warning message for TTS service that i dont use, as they fill my debug window.
Can a dummy settings be created or another setting where the warnings can be disabled?

Thanks for an awesome project. i Love it!

**Comment by Supergiovane** [comment]
Hi
it should log only at first nodered start. Can you show me your log please?

**Comment by plats98** [comment]
i get 3 debug logs every time i deploy any changes (even if i just move a comment node)
The only log i can find is this:

29.12.2021 23.30.25
msg : string[60]
"ttsultimate-config 9063d34ebdbb425b: Polly service not used."
29.12.2021 23.30.25msg : string[65]
"ttsultimate-config 9063d34ebdbb425b: Google TTS service not used."
29.12.2021 23.30.25msg : string[74]
"ttsultimate-config 9063d34ebdbb425b: Microsoft AzureTTS service not used. "

**Comment by Supergiovane** [comment]
Hi
Ok, this is how it is supposed to work. Don’t worry, as soon as you finished setup your node-red, you’ll have no more logs :-)

**Comment by Supergiovane** [comment]
V 1.0.37 is out in minutes with the log removed.
Just click here.
<img width="1102" alt="TTS_config_warnings_·_Issue__49_·_Supergiovane_node-red-contrib-tts-ultimate" src="https://user-images.githubusercontent.com/37666636/147736023-f71cf5d9-bba1-4c71-9627-3ae4b154b0ad.png">
