### ISSUE TITLE
Select Main Player via msg

### ISSUE THREAD

**Issue by TheOlli-knx-forum-de** [Supergiovane/node-red-contrib-tts-ultimate#5]
Hi Massimo,
do you think it's possible in one of the next versions to integrate a variable "msg.mainplayer" to select the Player via msg?
I would like to use your node in a subflow. Therfore it's neccessary to select the player via the input o the subflow.

BR

Olli

**Comment by Supergiovane** [comment]
Hi Olli
I’ll let you know.

**Comment by Supergiovane** [comment]
Anyway, for me, subflows are a total no-go. I’ll never use it again.

**Comment by Supergiovane** [comment]
Hi Olli
Are you able to test this file?
Please copy the attached zip's content, into .**node-red/node_modules/node-red-contrib-tts-ultimate/ttsultimate** folder and restart node-red.

Then, put this code into a function node and link it's output to the tts-ultimate, according to your scenario:

**If you don't have group of players:**

If you have group of players:
```
var config= {
    setMainPlayerIP:"192.168.1.109"
};
msg.setConfig = config;
return msg;
```

**If you have group of players:**

```
var config= {
    setMainPlayerIP:"192.168.1.109",
    setPlayerGroupArray:[
        "192.168.1.110",
        "192.168.1.111",
        "192.168.1.112"
    ]
};
msg.setConfig = config;
return msg;
```



[ttsultimate.js.zip](https://github.com/Supergiovane/node-red-contrib-tts-ultimate/files/5792475/ttsultimate.js.zip)

**Comment by TheOlli-knx-forum-de** [comment]
Hi Massimo,

 

works perfectly for me because I use fixed ip-adresses for all fixed devices.

I've tested it with four different players.

 

 

Thank you!

 


 

 

 

Olli

 


Gesendet: Sonntag, 10. Januar 2021 um 11:27 Uhr
Von: "Supergiovane" <notifications@github.com>
An: "Supergiovane/node-red-contrib-tts-ultimate" <node-red-contrib-tts-ultimate@noreply.github.com>
Cc: "TheOlli-knx-forum-de" <bodensee@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [Supergiovane/node-red-contrib-tts-ultimate] Select Main Player via msg (#5)


 

Hi Olli
Are you able to test this file?
Please copy the attached zip's content, into .node-red/node_modules/node-red-contrib-tts-ultimate/ttsultimate folder and restart node-red.

Then, put this code into a function node and link it's output to the tts-ultimate, according to your scenario:

If you don't have group of players:

If you have group of players:

var config= {
    setMainPlayerIP:"192.168.1.109"
};
msg.setConfig = config;
return msg;


If you have group of players:

var config= {
    setMainPlayerIP:"192.168.1.109",
    setPlayerGroupArray:[
        "192.168.1.110",
        "192.168.1.111",
        "192.168.1.112"
    ]
};
msg.setConfig = config;
return msg;


ttsultimate.js.zip

**Comment by Supergiovane** [comment]
Good Olli
Tomorrow i’ll roll out the new version an i’ll update the samples.
