### ISSUE TITLE
SONOS is unable to Connect to webserver

### ISSUE THREAD

**Issue by primpler** [Supergiovane/node-red-contrib-tts-ultimate#50]
Dear Supergiovane,

I am a user of the previoius sonospollytts which has been depreciated and is beging extended and contiuned under tts Ultimate. Unformtuantely, I am not able to get the node up an running as Sonos cannot connect to the Folder to play the downloaded mp3.

The old node sonospollytts still worls without any connection problem so I am sure it has to do something with the node or my misconfigurations.

**TTS-Ultimate Version**
1.0.36

Node-Red is being operated on a VM Ubuntu 20.04 machine

Thank you very much as I am more than happy to use the new node.

Best reagrds
Patrick

**Comment by Supergiovane** [comment]
Hi Patrik
TTS Ultimate works the same way as SonosPollyTTS. It downloads the TTS file, then serves it via HTTP to Sonos.
Can you please post a node-red log, so i can see what's happening?
Please bear in mind to totally disinstall Sonospollytts (as well as remove the config nodes) and restart node-red.

**Comment by primpler** [comment]
Hi Supergiovane, thank you very much for the quick reply.

I have uninstalled everything and restarted NODERED and it Works.

Thanks for such a nice node. All the best for 2022 and for some more nodes to some.

Best regards
Patrick

**Comment by Supergiovane** [comment]
Thanks Patrick. To you too!
