### ISSUE TITLE
TTS config reopen

### ISSUE THREAD

**Issue by plats98** [Supergiovane/node-red-contrib-tts-ultimate#51]
It is not supposed to do that. No other projects do not it and i need to disable it.  Why did you close the case when this issue was not resovled?

At the monemt im only using Google TTS whitout authentication. 
In an attemt to get the logs to disapeer i created a dummy Amazon configuration, but that resoveled in even more logs. 

How or where do i disable the logs below? is there some place i configure it? I know im not using the services and i'm fine whit that - just not logs. My other debuging is drawning in these logs.

Do i need to delete the project for it to reset?

30.12.2021 09.07.37
msg : string[60]
"ttsultimate-config 9063d34ebdbb425b: Polly service not used."
30.12.2021 09.07.37msg : string[65]
"ttsultimate-config 9063d34ebdbb425b: Google TTS service not used."
30.12.2021 09.07.37msg : string[74]
"ttsultimate-config 9063d34ebdbb425b: Microsoft AzureTTS service not used. "
30.12.2021 09.07.37msg : string[65]
"ttsultimate-config da48d04635322565: Google TTS service not used."
30.12.2021 09.07.37msg : string[76]
"ttsultimate-config da48d04635322565: Google Translate free service not used."
30.12.2021 09.07.37msg : string[74]
"ttsultimate-config da48d04635322565: Microsoft AzureTTS service not used. "
30.12.2021 09.08.48msg : string[164]
"ttsultimate-config da48d04635322565: Error getting polly voices CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1"
30.12.2021 09.08.49msg : string[60]
"ttsultimate-config 9063d34ebdbb425b: Polly service not used."
30.12.2021 09.08.49msg : string[65]
"ttsultimate-config 9063d34ebdbb425b: Google TTS service not used."
30.12.2021 09.08.49msg : string[74]
"ttsultimate-config 9063d34ebdbb425b: Microsoft AzureTTS service not used. "
30.12.2021 09.08.49msg : string[65]
"ttsultimate-config da48d04635322565: Google TTS service not used."
30.12.2021 09.08.49msg : string[76]
"ttsultimate-config da48d04635322565: Google Translate free service not used."
30.12.2021 09.08.49msg : string[74]
"ttsultimate-config da48d04635322565: Microsoft AzureTTS service not used. "

**Comment by Supergiovane** [comment]
Hi Plats
this is not an issue. If that log apperas only once on deploy, then you should be able to live with that. The log is supposed to log, not to be "mute" at all. If someone does have issues, how can i debug it without log?
As far as i can see, you have multiple configuration nodes, at least two. The node da48d04635322565 does have trouble with the credentials you set.

If you wish to have ZERO log, you can always set node-red not to log, but it's not a good idea.
Why you won't such log? Every node you install logs something, so you should ask every dev to disable the log. Better you do it by yourself in the node-red config.json file.

**Comment by plats98** [comment]
I was looking for a way to disable the logs. 

The reason for this is that the error im getting is "Microsoft AzureTTS service not used." 
When i have no node that use it, this message is irrelevant for me. 
if i configured a node that would use AzureTTS i would very much like to get the error. 
Like i did here: "Error getting polly voices CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1"
This is very helpfull :) i have now configured a node to use Polly, but i have not set it up correctly.

i dont use AzureTTS and i will never use it. therefore an error message every single time i press deploy is annorying me so much that im close to uninstalling it. 

I'm okay whit going to a config file to disable it manully - i just need to know where and how to do it :)

**Comment by plats98** [comment]
![error in tts-ultimate](https://user-images.githubusercontent.com/6020284/147735126-eb75b6a4-f5f4-49bc-b531-8b94e8fda5db.PNG)

**Comment by plats98** [comment]
The relevant debug information i need is completly lost in errors from TTS-Ultimate.

**Comment by Supergiovane** [comment]
Hi Patrick
You asking me to do a code change to avoid such log, appearing only when you deploy. This involves my time and my effort to do so, on a free and open source software i give for free.
You don't even starred my node!
If you al least star my node, i'll do it for you yet!

**Comment by plats98** [comment]
Hi

i just startede using node-red, and i would love to give you a star!
Where do i do that? ill give you max stars - i really love your product :)

**Comment by plats98** [comment]
Nevermind, i found it :)

**Comment by Supergiovane** [comment]
V. 1.0.37 will be out in minutes with the fix.
As you're new to node-red community, i suggest you to ever star a node you use.
This is a little "THANK" you give to the node's developer.
We code for free for the whole community and we're ever enthusiast when someone give us this little star. :-)

I close the issue. Let me know if you have other log problems.
