### ISSUE TITLE
OWNFILE NODE CONFIGURATION - VIEW SAMPLE CODE

### ISSUE THREAD

**Issue by plats98** [Supergiovane/node-red-contrib-tts-ultimate#52]
Hello 

Thanks agian for a super product :)
In the sample code for "ownfile" the type is wrong.

The correct type is "ownfileultimate", but the sample uses: "ownfile"

![sample tts-ultimate](https://user-images.githubusercontent.com/6020284/147735686-5f84a136-251e-4f39-aca3-966baa4ae8d5.PNG)

**Comment by Supergiovane** [comment]
Fixed with Version 1.0.38, out in minutes.
Thank you for pointing me out.
