### ISSUE TITLE
SSML, Voices

### ISSUE THREAD

**Issue by githubwesseln** [Supergiovane/node-red-contrib-tts-ultimate#53]
The SSML-Option doesn't work.
For example:
\<speak>
Guten Morgen Hans !
\</speak>

I can't choose voices for Google or Azure.

**Comment by Supergiovane** [comment]
Hi
please follow the issue template rule as i need more infos: https://github.com/Supergiovane/node-red-contrib-tts-ultimate/issues/new?assignees=Supergiovane&labels=&template=bug_report.md&title=

**Comment by githubwesseln** [comment]
Hi,

the tags where interpreted as text for Google or Azure

\<speak>
Guten Morgen Hans !
\</speak>

**TTS-Ultimate Version**
 - 1.0.37

**Are you running node-red behind homematic, docker or anything similar?**
 - Node-Red (V1.2.4) running in Docker on RaspberryPi

tts-ultimate node: 
![2022-01-01_133611](https://user-images.githubusercontent.com/61275073/147850768-94529b23-2ac9-436d-92d0-49582aa0c0fc.png)

payload:
![2022-01-01_134417](https://user-images.githubusercontent.com/61275073/147850829-c3b9bac3-cf1e-4b94-932e-c486ede02b98.png)

mp3-file:
![_SG7QW~3 MP3](https://user-images.githubusercontent.com/61275073/147850780-2d18d397-8a83-40d4-afd1-2ec4fb1017db.png)

**Comment by Supergiovane** [comment]
Hi!
Currently, ssml isnonly supported by Amazon Polly. 
I’m working on google implementation as well. Should be ready by the next version

**Comment by githubwesseln** [comment]
Hi,
ok, thanks for this info (I didn't use Amazon Polly).

If it is possible, I had a wish for the next version:
It is very usefull to configure the output directory for the mp3-files.
Actually I copy the files from the Docker ttsfiles-directory to the Docker-Web-Server (nginx or Apache) directory.

**Comment by Supergiovane** [comment]
Hi
Do you know that the node can output the tts mp3 file to the msg flow? You can use a “file” node to save it where you want!

**Comment by githubwesseln** [comment]
Hi,
no, I only see the filename(s) in the output (msg.filesArray[0..].file), so I copy the file(s).
How can I get the mp3-output ?

**Comment by Supergiovane** [comment]
It’s all wrote in the readme on github

**Comment by Supergiovane** [comment]
Hi
i see you're using google. I nee to know: are you using "Google TTS" or "Google without authentication" service?

**Comment by Supergiovane** [comment]
Anyway... the  "Google without authentication" doesn't support SSML. Please update to version 1.0.39 as soon as you see it in the palette, then use another TTS engine.
