### ISSUE TITLE
Last update broke sonos discovery

### ISSUE THREAD

**Issue by SebDominguez** [Supergiovane/node-red-contrib-tts-ultimate#55]
Hi there!

**Describe the bug**
Just updated to the last version of tts-ultimate ans unfortunately it seems that my sonos cannot see the endpoint at the port 1980 anymore.
**To Reproduce**
This is my `docker run` command

```
#! /bin/bash
docker run \
-d \
--restart unless-stopped \
-e "NODE_RED_CREDENTIAL_SECRET=XXX" \
-e "NODE_RED_CREDENTIAL_HASHED=XXX" \
--net=host \
-v $(pwd)/data:/data \
-e PUID=$(id -u) \
-e PGID=$(id -g) \
-e TZ=Europe/Madrid \
--name node-red \
nodered/node-red:latest
```

**Screenshots**
![IMG_6292](https://user-images.githubusercontent.com/52816569/157870361-89c502fe-ef43-49c5-b74f-d972c56f94e5.PNG)

**TTS-Ultimate Version**
 - V1.0.41

**Are you running node-red behind homematic, docker or anything similar?**
 - Node-red running inside a docker container

**Additional context**
I'm well aware of the networks problems that can occur when using a dockerized application. That's why I've used the `--net=host` option so the container share the network stack of the host so every ports and mdns stuff can pass through.

I've used the 1.0.20 so far and was able to use the node without problems.

**Comment by Supergiovane** [comment]
Hi
please check the port forwarding if you're in nat mode. Try also to change the port and restart node-red

**Comment by SebDominguez** [comment]
> Hi
> please check the port forwarding if you're in nat mode. Try also to change the port and restart node-red

I'm in host mode, and tried already 1981 port... I'm trying to rollback to 10.0.20

**Comment by Supergiovane** [comment]
Remember to always restart node-red after each change.

**Comment by SebDominguez** [comment]
I've restarted both the container and the host device

**Comment by SebDominguez** [comment]
I'm back at 10.0.20 with the exact same settings and all is working fine

I can even detect the sonos on the local network (with the 1.0.41 I had to use the fallback IP)


<img width="588" alt="Capture d’écran 2022-03-11 à 14 09 01" src="https://user-images.githubusercontent.com/52816569/157872576-23eaae5b-b759-426b-bae8-79e6ae0a34ff.png">

<img width="703" alt="Capture d’écran 2022-03-11 à 14 10 24" src="https://user-images.githubusercontent.com/52816569/157872685-59ecf6d0-401d-41ae-a0cb-30eaab57af8a.png">

**Comment by SebDominguez** [comment]
Is there any tests I can do to see what could have change with 1.0.41 that may have broke my container?

**Comment by Supergiovane** [comment]
Hi i don't know how your container works, so i cannot help you, but 1.0.41 should work, because the sonos engine is the same.
I suggest you to run a new docker from fresh and install the 1.0.41, to see if it works.
I strongly discourage using docker, because you really doesn't have any good control on the docker settings, node-red setting file in docker, etc.. Instead, you should use Virtual machine.

**Comment by SebDominguez** [comment]
Yeah VM should be better for compatibility purposes but the host that I'm using is resource limited so VM will be a bit wasteful...

I'm making a container from scratch and let you know how this is going
