### ISSUE TITLE
No configuration possible

### ISSUE THREAD

**Issue by fpalz** [Supergiovane/node-red-contrib-tts-ultimate#56]
Hi there,

i recently installed tts ultimate to my node red running on raspberry. 

Versions:
26 Mar 06:18:11 - [info] Node-RED version: v2.1.6
26 Mar 06:18:11 - [info] Node.js  version: v14.18.3
26 Mar 06:18:11 - [info] Linux 5.10.63-v7l+ arm LE

Unfortunately i`m not able to do a config for tts ultimate. It always tells:

THIS IS YOUR FIRST CONFIG-NODE
AND I NEED TO CREATE SOME THINGS
BEFORE LETTING YOU PROCEED.
PLEASE SAVE, FULL DEPLOY
AND RE-OPEN THIS WINDOW
TO BE ABLE TO FINISH THE CONFIGURATION SETUP

I really did everything. Reinstalling, rebooting, saving, deploying but i`m not able to do a configuration.Node red Debugging tells

"Missing Polly config"

Any ideas on it?

Thanks in advance!

**Comment by Supergiovane** [comment]
Are you able to do a video? If you follow what the node tells you, it should work.

**Comment by fpalz** [comment]
Unfortunately not at the moment. But i will give you a step-by-step description

Installed
Rebooted
Node added
Tried to open config - not possible
Stored
Deployed (all)
Tried to open config - not possible

Maybe i`m doing something totally wrong because of the early morning hours but i hope not.

**Comment by Supergiovane** [comment]
Hi
What tts engine are you using? Maybe the polly credentials aee incorrect. Try using the free google engine.

**Comment by Supergiovane** [comment]
Please see here:

https://user-images.githubusercontent.com/37666636/160230837-3818aaa4-43a9-4b95-ad01-0037143e9981.mov

**Comment by fpalz** [comment]
Sorry for beeing late! It was clearly my fault - Software is working perfect. Polly wasn`t installed in a proper way.

**Comment by Supergiovane** [comment]
Perfect, thanks for the feedback!
