### ISSUE TITLE
TTS with Node Red

### ISSUE THREAD

**Issue by Larson-Sei180LX** [Supergiovane/node-red-contrib-tts-ultimate#57]
Hey everybody,

thanks for that Node, its very useful for my needs. I have a question about Node Red and TTS, using this Node.

Can anybody explain, how to send my TTS Text in Node Red to the TTS-Ultimate-Node? I tried some ideas and with one opinion, it works fine. But I have to send my TTS messages in a style like this: _**"<speak>Hello world!</speak>"**_ 

I wouldnt like to use _**"<speak> ... </speak>"**_ in the beginning/ end. I only would like to write: **_Hello World!_**. But if I do like that, there is an TTS isue from Amazon Polly.

Maybe I need another function? At the moment I am using the "Trigger" event (see snapshot). Maybe I am using the wrong Function?
Thanks for help.

![Screenshot 2022-04-06 105419](https://user-images.githubusercontent.com/27363526/161936575-af923189-15f3-4c65-81ea-8bb30bd345c5.png)
.
![Screenshot 2022-04-06 105759](https://user-images.githubusercontent.com/27363526/161937202-18245bf3-6110-47e4-9b82-d85868f7c55e.png)

**Comment by Supergiovane** [comment]
Hi Larson
Wy do you use <speak> tag in the text?

**Comment by Larson-Sei180LX** [comment]
Otherwise i bekomme an issue from amazon… exactly that is the Problem - i dont want to use Tags

**Comment by Supergiovane** [comment]
You don't need to use the tags. Check the TTS node and disable the SSML option.

**Comment by Supergiovane** [comment]
Disable this, if enebled.
<img width="531" alt="Node-RED___192_168_1_217" src="https://user-images.githubusercontent.com/37666636/161957430-76d50225-894b-4730-90ea-92708af55fd4.png">

**Comment by Supergiovane** [comment]
Hey Larson,
are you still there?

**Comment by Larson-Sei180LX** [comment]
Yes. Still at work. Cant check it until tonorrow… hold on…thanks…will answer after my check

**Comment by Larson-Sei180LX** [comment]
Thank u you for help. That was exactly the problem ! Issue fixed:)!
