### ISSUE TITLE
Radio Stream does not resume after text played

### ISSUE THREAD

**Issue by fischkai** [Supergiovane/node-red-contrib-tts-ultimate#58]
Hello,

**Describe the bug**
Radio Stream does not resume after text played

**To Reproduce**
1. Play a radio stream on your sonos system (I have 4 speakers, main speaker called "sideboard")
2. Different radio streams play on the 4 speakers 
3. Play a text on all speakers at once (when I receive a phone call it tells me the callers name)
4. Radio streams get not resumed

Radio stream was resumed on the main speaker "sideboard" but that does not happen anymore.

**Expected behavior**
Radio streams should resume on all speakers

**Screenshots**
![Sonos](https://user-images.githubusercontent.com/6562713/164018814-8b04346e-a991-4689-bc9f-ffc8bcdf1d50.png)

**TTS-Ultimate Version**
 - 1.0.44

**Are you running node-red behind homematic, docker or anything similar?**
Node Red v 2.1.3 on a Raspberry Pi

**Comment by Supergiovane** [comment]
Hi
Does the radio stream resume on the main speaker at least?

**Comment by fischkai** [comment]
Yes, I just tried. It resumes on the main speaker.

**Comment by fischkai** [comment]
I do not care about a delay. It would be fine if it resumes all speakers on which a text was played.
Thank you for thinking about adding it to an upcoming version.

**Comment by Supergiovane** [comment]
Have you starred my node? :-)

**Comment by fischkai** [comment]
Of course :)

**Comment by Supergiovane** [comment]
Ok, i'll wrote here as soon as the new version is out.

**Comment by Supergiovane** [comment]
node-red-contrib-tts-ultimate@1.0.45 is out.
Please test it. It should work.

**Comment by fischkai** [comment]
Thank you, will test it. Node-Red is not offering it in the web-interface yet.

**Comment by fischkai** [comment]
Works! Great italian job!

**Comment by fischkai** [comment]
Ok, I have a little bit more experience with the new feature now. It's resuming the last streams on all sonos speakers which is perfect. Thank you. But if I press play in the Sonos app it's not showing the last stream but a stream I listened a long time ago. If I press play in the Sonos app it is playing the old stream. The stream which was resumed is not showing in the app.

**Comment by Supergiovane** [comment]
Hi
Yes. This is a known limitation. Controlling streams from the sonos API is very difficult. The API are undocumented and it’s hard to have a more accurate control over the so many stream types. I cannot do anything for that, sorry!
