### ISSUE TITLE
playback on sonos not possible

### ISSUE THREAD

**Issue by Christchoper** [Supergiovane/node-red-contrib-tts-ultimate#6]
After importing your example flow and adjusting the settings in the node ttsultimate, I get the following error message in Sonosplayer. 

![Bild](https://user-images.githubusercontent.com/76134962/103980543-580f6600-5180-11eb-9ca9-d2aa160a9c9c.png)

Where can I set the IP and port of the Node-Red?
Many thanks for your support

**Comment by Supergiovane** [comment]
Hi Chris
in the gitHub README, you'll find all infos. ;-)

<img width="932" alt="Supergiovane_node-red-contrib-tts-ultimate" src="https://user-images.githubusercontent.com/37666636/103982561-01a42680-5184-11eb-851a-edd19bd10d8e.png">

**Comment by Christchoper** [comment]
Thank you very much for the quick reply.
Sorry to ask, but where on the Red node can I make this setting?

**Comment by Supergiovane** [comment]
Simply double click on the tts-ultimate node, you'll see something like this:

<img width="532" alt="Node-RED___192_168_1_16" src="https://user-images.githubusercontent.com/37666636/103983216-2baa1880-5185-11eb-94e7-c842a9ceec66.png">

Click the button indicated by the blue arrow.
You'll see something like this.
See the blue arrow.

<img width="592" alt="Node-RED___192_168_1_16" src="https://user-images.githubusercontent.com/37666636/103983319-54caa900-5185-11eb-96ac-c7dc4505e592.png">

**Comment by Christchoper** [comment]
Sorry, I was asleep then! It's great how it works now.
Thanks for this awesome node.
Cheers, Chris
