### ISSUE TITLE
Latest version no longer restarting music queue 

### ISSUE THREAD

**Issue by tinimark** [Supergiovane/node-red-contrib-tts-ultimate#60]
**Salutation (i'll not respond to users that doesn’t wrote at least "Hello")**

**Describe the bug**
Latest version no longer restarting music queue 

**To Reproduce**
Music is playing on a Sonos ZP90
Ultimate TTS sends MP3 file to play on Sonos, this works but it doesn't return back to playing the music after.

**TTS-Ultimate Version**
1.0.49

**Are you running node-red behind homematic, docker or anything similar?**
Home Assistant OS 8.2

Was working fine until a recent update of tts-ultimate

**Comment by Supergiovane** [comment]
Hi Mark
Now i’m on holiday and cannot watch it, but i’ve received no compliants about that. Mine also resumes ok. 
Reinstall an older version of tts-ultimate until i come back from holiday. 
In the meantime, please send me your nodered log. Thanks.

**Comment by Supergiovane** [comment]
PS: Sonos ZP90 is a very old device, working on old api. Please consider to upgrade it.

**Comment by tinimark** [comment]
You're right it could probably do with replacing.
I'll try an older version of TTS and come back.
Have a great holiday!
