### ISSUE TITLE
About Support Chinese

### ISSUE THREAD

**Issue by songzh96** [Supergiovane/node-red-contrib-tts-ultimate#61]
Hi 
I chose the Chinese voice pack, which has expired. Do you support the new Chinese voice pack now?

**Comment by Supergiovane** [comment]
Hi songzh
What tts engine have you selected? Amazon? Google? Microsoft?

**Comment by songzh96** [comment]
Google
![image](https://user-images.githubusercontent.com/26770241/183239533-3a03e4bd-f76b-49f6-ad32-88838dfc6999.png)

**Comment by Supergiovane** [comment]
Hi again
Are uou using google paid tts, or the free google tts enfine?

**Comment by songzh96** [comment]
free google TTS engine

**Comment by Supergiovane** [comment]
It seems to be an issue in the chinese language code, that the google service returns. I’ve tried some tricks, without success. I’ve opened a ticket at google support about that. I’l keep you posted.

**Comment by Supergiovane** [comment]
I've hacked the google translate page and found a solution.
The new version will be out in some minutes. Please see in the node-red Palette.
Cheers.

**Comment by songzh96** [comment]
Thanks quick support.  
By the way, the tts node seems to conflict with the sonos-plus node.
