### ISSUE TITLE
tts-ultimate works but throwing errors. Hope someone can help interpret and suggest corrections

### ISSUE THREAD

**Issue by AgingTechNerd** [Supergiovane/node-red-contrib-tts-ultimate#62]
I'm running the Node Red plugin on Home Assistant on Rpi 3. I'm just getting the hang of it all and now trying to clean up my TTS announcements. I get the error below. TTS seemed to work ok so I figured I'd circle back and sort this error later but now I'm realising it's not returning the Sonos to as before. The main symptom is I'm finding one of My Sonos speakers is playing music from a previously selected source. I'm able to stop it in the Sonos app or in the HA Player controls. It seems random as to when it happens and which speaker is playing. If it's happening right after a TTS I've not witnessed it as the speakers it's happened on are in parts of the house we generally only pass through one a day or so. 

I'd like to get to know this node well and take advantage of the features. I've tried going through the docs and it's still a bit over my head. It seems to be a great node!

Hoping someone can help me decipher the error and suggest how I could resolve it. 

Much appreciated. 

Thanks

<img width="1024" alt="Screen Shot 2022-08-25 at 12 59 10 PM" src="https://user-images.githubusercontent.com/108820697/186725753-ab39d87b-afa5-4561-aaa5-be729139f60d.png">

```
"ttsultimate: Error joining device upnp: statusCode 500 & upnpErrorCode <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>402</errorCode></UPnPError></detail></s:Fault></s:Body></s:Envelope>"
```
<img width="449" alt="Screen Shot 2022-08-25 at 1 14 07 PM" src="https://user-images.githubusercontent.com/108820697/186728419-ed6c217d-cc6a-4c74-8063-a2f6eb874afb.png">

**Comment by Supergiovane** [comment]
Hi
You must choose a main player as well!

**Comment by AgingTechNerd** [comment]
Oops! DIsregard the previous screenshot. The main player had been unplugged momentarily. 

Here's how it is as the moment and the error persists with the main player selected. I've tried it with various main player selections and still the error persists. 

Any further insights? I'm also hoping to change the voice. I've changed the voice options but the voice always sounds the same. American English Femail. 

Much appreciated. 

```
"ttsultimate: Error joining device upnp: statusCode 500 & upnpErrorCode <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>402</errorCode></UPnPError></detail></s:Fault></s:Body></s:Envelope>"
```
<img width="450" alt="Screen Shot 2022-08-26 at 10 59 44 AM" src="https://user-images.githubusercontent.com/108820697/186934955-ee323a8c-576f-4098-848c-7b5797007968.png">

**Comment by Supergiovane** [comment]
Hi
You must be sure that HA forwards all ports needed, to nodered. I suggest you to ask someone on the HA forum, as i don’t use HA, sorry! As per the voices, try to restart nodered.

**Comment by AgingTechNerd** [comment]
ok will do. 

FYI I just tried calling Sonos support just to make sure all my speakers were configured and grouped correctly. The speaker I had originally selected as master had somehow been renamed from "Dining Room" to "Kitchen 2". I corrected that I restarted HA/Node Red, reviewed the sonos assignments in TTS-Ultimate and I still get the following error:

```
"ttsultimate: Error joining device upnp: statusCode 500 & upnpErrorCode <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>402</errorCode></UPnPError></detail></s:Fault></s:Body></s:Envelope>"
```
<img width="451" alt="Screen Shot 2022-08-26 at 12 51 41 PM" src="https://user-images.githubusercontent.com/108820697/186954372-49d98602-5c11-4c80-8c36-249e3ff36dc4.png">


Also FYI .. I had made the following post when I was just starting adding TTS to my system... that's how I learned about TTS-Ultimate. There was no reply after so I'll try again making a fresh post with newly restated question. 

(https://community.home-assistant.io/t/ha-node-red-rpi-sonos-how-to-get-access-nabu-casa-tts-configured-in-ha-for-use-in-node-red/446079)

I'll circle back and post the outcome when I have a solution. 

If in the meantime anyone else finds this thread and can help it would be greatly appreciated. 

Thanks!

**Comment by Supergiovane** [comment]
You could try to install a clean nodered on uour pc or any spare raspberry, or in a VM and test it. Mine is working fine, but don’t use HA

**Comment by AgingTechNerd** [comment]
I'm still just finding my way around Node Red and HA. I'm not Coming off HomeSeer3 Rpi so converting the logic over. So far this is the only snag i've hit. At some point i"ll build up Node Red in a test environment after I get the last of the automation tasks off HomeSeer (i'm 80% there!)

I've have a love/hate relationship with HomeSeer over the last 20 years or so (prior to that I had. love/hate relationship with X10/Enerlogic). I'm glad to leave it and all it's flakiness behind. Home Assistant seems to be spot on. 

If a tts-ultimate solution doesn't come my way in a few weeks I'll go back to try getting the Call Service Node to use the TTS options in HA cloud.  

Thanks for the time you put into this and the quick replies!

**Comment by AgingTechNerd** [comment]
> You could try to install a clean nodered on uour pc or any spare raspberry, or in a VM and test it. Mine is working fine, but don’t use HA

Actually I was just looking over my application of tts-ultimate... I have 3 separate flows feeding 3 tts-ultimate nodes. Is that ok or should I try to set up connectors and funnel everything into just one tts-ultimate node?

**Comment by Supergiovane** [comment]
Hi
It’s ok to have multiple tts nodes. TTS-Ultimate handles the priority automatically. 
You’ll enjoy nodered, because it’s a swiss knife! But start with a clean install. Homeassistant uses a sorr of “pluggerized” nodered and you have to know how to handle that. 
I also used Homeseer. I wrote some plugins for HS in the years 2005-2009, the most famous was the backup plugin.
