### ISSUE TITLE
Problem with own mp3 Files

### ISSUE THREAD

**Issue by Saranger85** [Supergiovane/node-red-contrib-tts-ultimate#64]
i hope you can help me for using ttsultimate, i don't found a instruction that can help me. I want to upload an own mp3 file for a doorbell. what is the right configuration for using without tss engine, i only want to hear the mp3 file.?

`[
    {
        "id": "2014dda94e059b86",
        "type": "tab",
        "label": "Flow 2",
        "disabled": false,
        "info": "",
        "env": []
    },
    {
        "id": "44cdcfc099908b84",
        "type": "ttsultimate",
        "z": "2014dda94e059b86",
        "name": "",
        "voice": "Vicki#engineType:standard",
        "ssml": false,
        "sonosipaddress": "192.168.2.163",
        "sonosvolume": "40",
        "sonoshailing": "Hailing_dorbell1.mp3",
        "config": "4d0df6560e582ece",
        "property": "payload",
        "propertyType": {},
        "rules": [
            {
                "host": "192.168.2.163",
                "hostVolumeAdjust": "0"
            }
        ],
        "playertype": "sonos",
        "speakingrate": "1",
        "speakingpitch": "0",
        "unmuteIfMuted": true,
        "x": 930,
        "y": 260,
        "wires": [
            [
                "bdfef51bf9562125"
            ],
            [
                "02f2404ff29328bd"
            ]
        ]
    },
    {
        "id": "eb9b6582c8eae755",
        "type": "knxUltimate",
        "z": "2014dda94e059b86",
        "server": "6fc013af.98132c",
        "topic": "2/1/97",
        "outputtopic": "",
        "dpt": "1.002",
        "initialread": 0,
        "notifyreadrequest": false,
        "notifyresponse": false,
        "notifywrite": true,
        "notifyreadrequestalsorespondtobus": false,
        "notifyreadrequestalsorespondtobusdefaultvalueifnotinitialized": "0",
        "listenallga": false,
        "name": "Klingel",
        "outputtype": "write",
        "outputRBE": true,
        "inputRBE": false,
        "formatmultiplyvalue": 1,
        "formatnegativevalue": "leave",
        "formatdecimalsvalue": 999,
        "passthrough": "no",
        "x": 250,
        "y": 260,
        "wires": [
            [
                "9512a5029ea40c6d"
            ]
        ]
    },
    {
        "id": "bdfef51bf9562125",
        "type": "debug",
        "z": "2014dda94e059b86",
        "name": "Nachricht gespielt",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 1170,
        "y": 240,
        "wires": []
    },
    {
        "id": "02f2404ff29328bd",
        "type": "debug",
        "z": "2014dda94e059b86",
        "name": "Error",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "payload",
        "targetType": "msg",
        "statusVal": "",
        "statusType": "auto",
        "x": 1150,
        "y": 300,
        "wires": []
    },
    {
        "id": "cfd5eb82a07a99a1",
        "type": "change",
        "z": "2014dda94e059b86",
        "name": "Icon Closed",
        "rules": [
            {
                "t": "set",
                "p": "payload",
                "pt": "msg",
                "to": "",
                "tot": "str"
            }
        ],
        "action": "",
        "property": "",
        "from": "",
        "to": "",
        "reg": false,
        "x": 710,
        "y": 260,
        "wires": [
            [
                "44cdcfc099908b84"
            ]
        ]
    },
    {
        "id": "9512a5029ea40c6d",
        "type": "switch",
        "z": "2014dda94e059b86",
        "name": "",
        "property": "payload",
        "propertyType": "msg",
        "rules": [
            {
                "t": "true"
            },
            {
                "t": "false"
            }
        ],
        "checkall": "true",
        "repair": false,
        "outputs": 2,
        "x": 530,
        "y": 260,
        "wires": [
            [],
            [
                "cfd5eb82a07a99a1"
            ]
        ]
    },
    {
        "id": "4d0df6560e582ece",
        "type": "ttsultimate-config",
        "name": "Polly",
        "noderedipaddress": "192.168.2.120",
        "noderedport": "2010",
        "purgediratrestart": "purge",
        "ttsservice": "polly",
        "TTSRootFolderPath": ""
    },
    {
        "id": "6fc013af.98132c",
        "type": "knxUltimate-config",
        "host": "192.168.2.146",
        "port": "3671",
        "physAddr": "15.15.22",
        "suppressACKRequest": true,
        "csv": "",
        "KNXEthInterface": "Auto",
        "KNXEthInterfaceManuallyInput": "",
        "statusDisplayLastUpdate": true,
        "statusDisplayDeviceNameWhenALL": true,
        "statusDisplayDataPoint": false,
        "stopETSImportIfNoDatapoint": "stop",
        "loglevel": "error",
        "name": "Martins KNX",
        "localEchoInTunneling": true,
        "delaybetweentelegrams": "40",
        "delaybetweentelegramsfurtherdelayREAD": "1",
        "ignoreTelegramsWithRepeatedFlag": false,
        "keyringFileXML": ""
    }
]`

and when i use Amazon polly i hear the messe but i got this debug every time

`"ttsultimate: Error joining device upnp: statusCode 500 & upnpErrorCode <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>402</errorCode></UPnPError></detail></s:Fault></s:Body></s:Envelope>"`

Thank you

best regards

**Comment by Supergiovane** [comment]
Hi
for custom files, you must use the OwnFile node.
Please see the rEADME in gitHub and scroll down until you find the istructions for the ownfile node. There is an example as well

<img width="769" alt="Istantanea_13_12_22__09_28" src="https://user-images.githubusercontent.com/37666636/207264862-e05e3237-c5aa-408a-853e-1a82f020af27.png">


Based on that, your flow should look like this:
<img width="700" alt="Istantanea_13_12_22__09_31" src="https://user-images.githubusercontent.com/37666636/207265516-218c5346-5df0-49bb-831c-d5cde0d431e4.png">
