### ISSUE TITLE
Main Sonos Player Dropdown Displays Speakers as a Group

### ISSUE THREAD

**Issue by kars85** [Supergiovane/node-red-contrib-tts-ultimate#65]
Hello!

**Describe the bug**
I've noticed inconsistent behavior with the menu drop down for speaker selection. My main player has a static reservation on my router outside of my DHCP scope, FWIW. However, the drop down "bundles" that main player with my other speakers sometimes. These other speakers are not static IP'd.

**To Reproduce**
Unknown and the issue isn't clear on how to reproduce - I've restarted the docker nodered container but can't get the Main Sonos player drop down, or the dropdown under additional players to list out the grouped speakers individually

**Expected behavior**
I'm thinking the expected behavior is to **not** have the drop down display speaker groups, and instead have them listed out individually?

**Screenshots**
![image](https://user-images.githubusercontent.com/6616548/222135691-a876b77a-c753-4912-b5d8-6f7837448e0b.png)

**TTS-Ultimate Version**
1.0.52

**Are you running node-red behind homematic, docker or anything similar?**
Docker in host networking mode

**Comment by kars85** [comment]
Thanks for the reply! I think the confusion is highlighted in the picture. The Kitchen Sonos +2 is not intended as it's hiding the Master Bedroom Sonos and Shop Sonos, and instead, grouping them together. I don't want to broadcast to those devices.

**Comment by Supergiovane** [comment]
Hi Kars
Understood. I’ll try to reply that and find a way to show the single sonos speakers…
I’ll let you know asap…

**Comment by Supergiovane** [comment]
Hi Kars
Fixed in 1.0.53.
You should see it in the palette in about 1 hour.

**Comment by Supergiovane** [comment]
Hi
currently, it's a little difficult to determine whether a sonos player is part of a group or not, so you see many duplicates.
I'm looking on that, to be able at least to filter out duplicate IPs.

**Comment by Supergiovane** [comment]
node-red-contrib-tts-ultimate@1.0.55 is out with de-duplication function. Currently, this is at best, what i can do.
