### ISSUE TITLE
OwnFile (mp3) not playing until end

### ISSUE THREAD

**Issue by Hypoferalcus** [Supergiovane/node-red-contrib-tts-ultimate#66]
Hi Supergiovane!

Thanks so much for your amazing nodes - tts ultimate and especially knx ultimate work great!

Now we tried to use the ownfile node as well and uploaded a 3 minute mp3 (a music song)
It starts to play fine but after some time (roughly about half a minute) it just fades out and doesn't play the song until the end.
There was nothing in the queue before (i.e. there is a TTS a few seconds earlier - but that just plays until the end and after a few seconds the ownfile starts) - and it is just silence after the "fade-out"

Are we doing anything wrong here, do we need a different config or is this intentional?

NodeRed runs on Docker and tts-ultimate node is v. 1.0.52

We would really appreciate your help and a possible solution

**Comment by Supergiovane** [comment]
Hi
Never tested with a so long file. 
tomowwor i’ll take a look !

**Comment by Supergiovane** [comment]
Hi
Please try ode-red-contrib-tts-ultimate@1.0.54 and let me know.
Thanks.

**Comment by Hypoferalcus** [comment]
I just update and - it works now! Great!

Thank you for that super-fast fix and update!
