### ISSUE TITLE
Feature Request: Ability to change the 'payload' flag

### ISSUE THREAD

**Issue by leacho73** [Supergiovane/node-red-contrib-tts-ultimate#68]
Hi,

Sorry, I'm unable to raise a feature request - so please feel free to bin this off if its not the right channel.

Would it be possible in the future to change the 'payload' tag when a message is sent?

Currently, I am passing through something similar to your example:

```
// Play a message
msg.payload = "Hello, the current temperature is 12°";
return msg;
```

However, I am using a switch to direct the message to a specific room - which could be a Sonos or Alexa device - and I'd like the ability to tag the message in the Node-Red flow - like msg.fridgeisopenmsg for example?

Is this possible?

Thanks
Leacho

**Comment by Supergiovane** [comment]
Hi
You could simply add a “change” node, to assign the payload to a different property. 
Can you paste here your flow, so i can take a look at what you’re looking for?
Thanks.
