### ISSUE TITLE
Additional speaker sometimes not fully playing announcement

### ISSUE THREAD

**Issue by georgr** [Supergiovane/node-red-contrib-tts-ultimate#7]
Main speaker always plays announcment fully, second speaker added via additional speakers sometimes misses the first 500ms or so, but plays the rest synchronized with the main speaker. 

You can hear in the sample added in the attachment as the second speaker chimes in a bit louder.

[sample.zip](https://github.com/Supergiovane/node-red-contrib-tts-ultimate/files/5790507/sample.zip)

**Comment by Supergiovane** [comment]
Thanks for the salutation. 😒 
I’ll take a look. I’ll maybe add a slightly delay after the grouping has completed and before playing. 
I cannot control how Sonos internally handles sync.

**Comment by georgr** [comment]
Sorry, I got pointed out too often not to salute in issues and only write what is necessary, therefore I broke the habit. 

But it is not meant as unfriendly, I love your work and dedication to the project!

**Comment by Supergiovane** [comment]
Hello Georg,
yes, i know, but we italians do love such things, like warming salutation. Don't worry.
Please copy the attached zip's content you find [here](https://github.com/Supergiovane/node-red-contrib-tts-ultimate/issues/5#issuecomment-757452184), into **.node-red/node_modules/node-red-contrib-tts-ultimate/ttsultimate** folder and restart node-red.
Then check if the issue has been resolved.
Thanks.

**Comment by georgr** [comment]
Hi Giovane,

looks perfect at the first tests. I´ll observe it for a week and post you the results!

Thank you!
