### ISSUE TITLE
REQ: Can we add ElevenLabs API to this?

### ISSUE THREAD

**Issue by MikeKMiller** [Supergiovane/node-red-contrib-tts-ultimate#71]
It would be terrific if we could get ElevenLabs added to this, as it is currently one of, if not the best TTS engine available.

**Comment by Supergiovane** [comment]
Hi
Interesting... I'll pin this request.
I'm upgrading all services on the TTS node and if able, i'll add that.

**Comment by MikeKMiller** [comment]
Thanks!!

To make this simpler you may be able to use this npm package.

https://github.com/FelixWaweru/elevenlabs-node

**Comment by MikeKMiller** [comment]
That was fast!! I will check it out. Thank you!
