### ISSUE TITLE
Is there anyway to speed up the response?

### ISSUE THREAD

**Issue by xnaron** [Supergiovane/node-red-contrib-tts-ultimate#74]
Hello and thank you for taking the time to make this.

It takes 2 to 3 seconds to return even when the file is cached.  I have it set to just return the filename so I can use the mp3 file in my own audio setup.

I'm running v2.0.4 of tts ultimate in node-red v3.0.2 in ubuntu in a docker container running on bare metal pc hardware.

I there a way to speed up the response or a way for me to debug why it is taking so long?

Thanks,

**Comment by Supergiovane** [comment]
Hi
I’ll take a look. 
If I’ve understood correctly, you’re using the node without Sonos, right?

**Comment by xnaron** [comment]
Thanks and yes without Sonos.

**Comment by Supergiovane** [comment]
node-red-contrib-tts-ultimate@2.0.5 is out with the fix.
You should see it in minutes, in the palette.

**Comment by Semetra22** [comment]
@xnaron @Supergiovane 
Sorry for the question, but how do I get the filename? 
A debug node after the TTS node only gives me msg.payload false and shortly after msg.payload true.

**Comment by Supergiovane** [comment]
Hi
The node should output an array of filepaths in the msg object.

<img width="468" alt="Node-RED___Antifurto" src="https://github.com/Supergiovane/node-red-contrib-tts-ultimate/assets/37666636/257dac1b-1380-4801-82d3-91f5eed8c389">
