### ISSUE TITLE
Send TTS to a local or many local Amazon Echo devices instead of SONOS?

### ISSUE THREAD

**Issue by HeinzRuetschi** [Supergiovane/node-red-contrib-tts-ultimate#75]
Hi Supergiovane, 
is it possible with your Node-RED note to send TTS output to one or many local Amazon Echo devices in the home network instead of the SONOS devices?
I would like to send TTS messages to local echo’s without using any external server.
I'm aware of some notes like Remote2 etc.
Do you have any recommendation, how to do that?
Thank you for any advice or clever feedback.
Kind regards
Heinz Ruetschi

**Comment by Supergiovane** [comment]
Hello,
i'm unaware, how to send the audio to echo speakers.
The node can generate the file (without sending it to Sonos), but that is.
Anyway, i'll buy an echo speaker and i'll do some test...

**Comment by HeinzRuetschi** [comment]
Hey Massimo, thank you very much for your super-fast reply and support...!
