### ISSUE TITLE
Hi Supergiovane,

### ISSUE THREAD

**Issue by basterl** [Supergiovane/node-red-contrib-tts-ultimate#76]
**Salutation (i'll not respond to users that doesn’t wrote at least "Hello")**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**TTS-Ultimate Version**
 - Eg. 1.1.95

**Are you running node-red behind homematic, docker or anything similar?**
 - Eg. Node-Red running alone in RaspberryPi

**Additional context**

**Comment by basterl** [comment]
Hi,
thank you for the nodered nodes . I install your node on an docker node red.
After installing the node i can fill in in the tts service with amazon polly. After i deploy and restart nodered, i get the following message from node red: 
Flows gestoppt aufgrund fehlender Node-Typen (Flows stopped due to missing node types:    ttsultimate-config

my flow is : bell ->fritzbox ->tts-ultimate ->sonos

with the previous version did it work.

In the setting;
node-red-contrib-tts-ultimate
2.0.5
SyntaxError: Unexpected identifier (line:18)

![grafik](https://github.com/Supergiovane/node-red-contrib-tts-ultimate/assets/147587113/e6df4ee8-5d88-47fc-a214-a88a901cce0b)
![grafik](https://github.com/Supergiovane/node-red-contrib-tts-ultimate/assets/147587113/33999b59-b713-470c-9e70-4def5a64564d)
![grafik](https://github.com/Supergiovane/node-red-contrib-tts-ultimate/assets/147587113/8ae3107a-24f1-49d1-8fc1-a5e02f08dd80)
![grafik](https://github.com/Supergiovane/node-red-contrib-tts-ultimate/assets/147587113/674d7e9c-baac-4d24-a23b-8b2a2df4bf4a)


Thanks for your support.

Greetings basterl

**Comment by Supergiovane** [comment]
Hi
What version of node.js and nodered are you using?
That “syntax error” doesn’t sound good.

**Comment by Supergiovane** [comment]
Nodered version: you can find it in the nodered menu on the right

Node.js: write “node -v” in a command prompt.

**Comment by basterl** [comment]
![grafik](https://github.com/Supergiovane/node-red-contrib-tts-ultimate/assets/147587113/9ca971fe-b98e-4665-8e79-a39ab257cf34)

**Comment by basterl** [comment]
![grafik](https://github.com/Supergiovane/node-red-contrib-tts-ultimate/assets/147587113/ea7c4617-82fd-4a05-aaef-1674e75204fd)

**Comment by basterl** [comment]
oh oh i see a lot of updates... sorry for the circumstances

**Comment by Supergiovane** [comment]
Hi
Yes
you need to install at least node.js 16.x or 18.x and at least node-red  v3.0.0

**Comment by basterl** [comment]
Thank you for your work. I updated to the latest. Now it work. 
Greetings from Germany.

**Comment by Supergiovane** [comment]
Vielen Dank für die Info.
Gruß aus Italien.
