### ISSUE TITLE
Error with Amazon Polly

### ISSUE THREAD

**Issue by pshellguruwannabe** [Supergiovane/node-red-contrib-tts-ultimate#8]
I created an access key and secret key.  created the config and put the info in, and it always returns this:

"ttsultimate-config: Error getting polly voices CredentialsError: Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1"

**Comment by Supergiovane** [comment]
Hello to you too 
Please double check the credentials for spaces after and before. 
In the readme on github, there is a link to a german how-to on how to register to aws polly.

**Comment by pshellguruwannabe** [comment]
HI @Supergiovane.  I've double checked the credentials, and they are good.  no spaces.  It looks like in the browser that the secret key isn't being retained to get saved.  I'm using Chrome.  I did notice (and this may not be anything) that when i paste the secret key in the field, it shows the full length, but after updating it and doing a full deploy, it shows a much shorter secret key.  i'm attaching some pics of that so you can see.  
![enter_password](https://user-images.githubusercontent.com/7200507/104391879-7ff72480-5506-11eb-9f7c-6de6c1b878a6.png)
![enter_password_after_deploy](https://user-images.githubusercontent.com/7200507/104391880-808fbb00-5506-11eb-844b-1f6fe66789e3.png)

**Comment by Supergiovane** [comment]
Hi
this is normal. All passwords on browser’s fields appears shorter after you’ve set it. 
Try to restart nodered.

**Comment by Supergiovane** [comment]
Another thing: do you maybe have unusual chars in the password?

**Comment by pshellguruwannabe** [comment]
> Another thing: do you maybe have unusual chars in the password?

no unusual characters.  all upper and lower case letters and numbers.

**Comment by pshellguruwannabe** [comment]
Well, i'm getting a different error this morning.

"ttsultimate-config: Error getting polly voices InvalidSignatureException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details."

**Comment by Supergiovane** [comment]
Hi Ps
That error comes directly from Amazon AWS. It's not related to tts-ultimate.
You should do what Amazon asks you. Have you followed this tutorial https://technikkram.net/blog/2020/09/26/sonos-sprachausgabe-mit-raspberry-pi-node-red-und-amazon-polly-fuer-homematic-oder-knx-systeme ?

**Comment by pshellguruwannabe** [comment]
> Hi Ps
> That error comes directly from Amazon AWS. It's not related to tts-ultimate.
> You should do what Amazon asks you. Have you followed this tutorial https://technikkram.net/blog/2020/09/26/sonos-sprachausgabe-mit-raspberry-pi-node-red-und-amazon-polly-fuer-homematic-oder-knx-systeme ?

I have.  So, i think i have this fixed.  I created a new key, put the new creds in and did a full deploy of the flows.  still got the error.  I restarted Node-Red and now everything seems to be working.

**Comment by Supergiovane** [comment]
Well done!

**Comment by pshellguruwannabe** [comment]
Thanks for creating this package and thanks for the prompt support!!!
