### ISSUE TITLE
Disable log entries

### ISSUE THREAD

**Issue by Graefer** [Supergiovane/node-red-contrib-tts-ultimate#81]
Hi, 
using version 2.0.5. The NodeRed log shows lots of infos, that hailing was disabled which is IMHO irrelevant and makes the log a bit confusing. Was it possible to (optionally) disable those log entries?
BTW: What is the function of the ‚disable‘ button next to the hailing preferences in the configuration window?
Gracie
Graefer

**Comment by Supergiovane** [comment]
Hi Graefe
About "disable" button, it's actually "delete". You can delete any hailing you want.
A little bit lower, there is an "upload hail" button, to upload a new hail.

<img width="631" alt="Node-RED___192_168_1_16" src="https://github.com/Supergiovane/node-red-contrib-tts-ultimate/assets/37666636/14fc6966-217f-457c-86af-e39d1e7fbb6c">

About log:
Many logs you see, are coming from the proprietary TTS library. 
There is currently no options to fully silence the logs, but the majority of te logging, happens during node-red boot, so not a big issue in the long run!

**Comment by Supergiovane** [comment]
PS: the node uses the native RED.log library for logging. You can silence the logs directly in the node-red settings.

**Comment by Supergiovane** [comment]
Here the direct Link for setting the loglevel. https://nodered.org/docs/user-guide/runtime/logging
If you've any other questions, just ask.
