### ISSUE TITLE
I cant reach my sonos speaker that are located on another vlan.

### ISSUE THREAD

**Issue by ulferi** [Supergiovane/node-red-contrib-tts-ultimate#83]
Hello!
Im impressed by your project.

I cant reach my sonos speaker that are located on another vlan.
I have port 1980 open in firewall
It says playing
Then no queue

What to do!

**Comment by Supergiovane** [comment]
Hi
Hmmm....
I thing you should pass UDP packets and maybe MDNS between vlans. You could ask somewhere in Unifi forum or other lan related tech forums...
I cannot help you in that, sorry!
