### ISSUE TITLE
"Additional players" no longer working

### ISSUE THREAD

**Issue by Hypoferalcus** [Supergiovane/node-red-contrib-tts-ultimate#88]
Hi there!

For some days or maybe weeks the tts-node only sends the voice to the "main" sonos player but no longer to the additional players configured in that node. It did work before and we didn't change anything I'm aware of.
When I swap the "main" player with one of the additional players it only works on the now "new" main player, so there is no problem with the connection between node red/ultimate tts and the sonos speakers in principal.
Is there any known issue about that?

I'm running node-red-contrib-tts-ultimate 2.0.7 in a node red docker container (NR v 4.0.2)

![grafik](https://github.com/user-attachments/assets/13573eab-cbde-4624-acf3-4c144c60d1f4)

Thanks for looking into it!

kind regards

**Comment by Supergiovane** [comment]
Hi
Mine is working flawlessy since about 2 years. 
No know issues.  
Maybe a new firmware automatically installed on the Sonos players?
I need to see the node-red log. Are you able to grab it and paste it here?

**Comment by Hypoferalcus** [comment]
Hi there
The firmware is the same on all sonos players and as I said, whatever sonos I put in as "main" works fine - only the "additional" ones don't do anything. But the same ones that don't work as "additional" ones in fact DO work, once I put one in as "main".

I'll happily provide everything you need - unfortunately I'm not sure - even after a bit of research - how I would get that log. I run node red as docker on photon os - do you happen to have a guide how to extract that log?

**Comment by Supergiovane** [comment]
Hi
just issue this command: node-red-log -n 2000
I’m not an expert on photon os, but the command should be the same.

**Comment by Hypoferalcus** [comment]
It doesn't seem to be so easy to export that log under photon os - but I have some other strange issues with sonos. I will first try to rule out, that it is in fact a problem with sonos and get back to you then!
