### ISSUE TITLE
Getting full url from response

### ISSUE THREAD

**Issue by Fernando-Checa** [Supergiovane/node-red-contrib-tts-ultimate#89]
Hello,

When the node is run I get a response from TTS with an MP3 file, and the local URL like:

`/data/sonospollyttsstorage/hailingpermanentfiles/Hailing_ComputerCall.mp3`

But in order to send the file to another player, I need the absolute URL.

How can I get that? So I can fetch the file from another player in the network.

Thanks in advance

**Comment by Fernando-Checa** [comment]
I tried something like this but it does not work

`http://192.168.1.213:1880/data/sonospollyttsstorage/hailingpermanentfiles/Hailing_ComputerCall.mp3`

**Comment by Supergiovane** [comment]
Hi
you need to serve the file via your own implementation, for example by using an http package.

**Comment by Fernando-Checa** [comment]
Will try that. Thanks again
