### ISSUE TITLE
playback is not resumed

### ISSUE THREAD

**Issue by Fernando-Checa** [Supergiovane/node-red-contrib-tts-ultimate#90]
Good morning,

I'm doing some testing with this great node but I have a problem.

If I'm playing music on the main speaker, when I send a message, the music stops, plays the message but it never resumes the music.

Maybe I'm doing something wrong here.

I'm also trying to take a snap before sending the audio so I can restore to it's previous state. But so far no luck.

**Comment by Fernando-Checa** [comment]
It's weird. Sometimes it resumes sometimes not.

I made a flow like this so it resumes every time no matter what

![CleanShot 2024-09-25 at 14 46 05](https://github.com/user-attachments/assets/1b78cd80-6b6e-4eda-962c-f29211dbda5c)

When I captures this image it did resume correctly as you can see, but since the play.snap resumes again, it does not matter if the stream is already playing

**Comment by Fernando-Checa** [comment]
This is the config. Sonos is configured with static IP
![CleanShot 2024-09-25 at 14 57 53](https://github.com/user-attachments/assets/25eae5f1-56a7-44a0-ac38-f79d83e2af2b)

**Comment by Supergiovane** [comment]
Hi
does the main sonos player have a fixed IP? It's required to have a fixed IP, either via DHCP reservation or manually set it to a fixed one.

**Comment by Fernando-Checa** [comment]
Yes, I only have one sonos connected and it has fixed IP

**Comment by Fernando-Checa** [comment]
this is from the logs

`25 Sep 14:49:49 - [info] Started modified nodes
25 Sep 14:49:49 - [info] ttsultimate: ZONE COORDINATOR "Salón"
25 Sep 14:50:24 - [warn] ttsultimate-config ca1dcaeed5536bc9: Error in discovery Error: No device found
25 Sep 14:55:03 - [warn] ttsultimate-config ca1dcaeed5536bc9: Error in discovery Error: No device found`

**Comment by Supergiovane** [comment]
That's the auto discovery protocol. You can just ignore it.

**Comment by Fernando-Checa** [comment]
I have another error.. :-S

I think I deleted a hailing file from the interface and selected another.
Now the announcements work fine with the new sound but I get this error from the old file..

![CleanShot 2024-09-25 at 15 17 01](https://github.com/user-attachments/assets/575ca7b6-8fcc-4432-801b-c6dd4ff6f8cb)


`25 Sep 15:15:34 - [info] Started modified nodes
25 Sep 15:15:42 - [info] ttsultimate: Hailing .MP3, skip tts, filename: Hailing_positive-notification.mp3
Salvelox /data/sonospollyttsstorage/ttsfiles/3761f9cbc0620a85200b308f4e356f2a.mp3
Salvelox /data/sonospollyttsstorage/ttsfiles/858fcac8b6b0d8139af6f94e1a89eab3.mp3
25 Sep 15:16:01 - [error] ttsultimate-config ca1dcaeed5536bc9: Playsonos RED.httpAdmin file not found: %2Fdata%2Fsonospollyttsstorage%2Fhailingpermanentfiles%2FHailing_positive-notification.mp3
25 Sep 15:16:01 - [error] ttsultimate-config ca1dcaeed5536bc9: Playsonos RED.httpAdmin file not found: %2Fdata%2Fsonospollyttsstorage%2Fhailingpermanentfiles%2FHailing_positive-notification.mp3
25 Sep 15:16:30 - [info] Stopping modified nodes`

really weird..
maybe a nodered restart will fix this

**Comment by Fernando-Checa** [comment]
Well, uploaded a file with that name and it stopped complaining.

**Comment by Fernando-Checa** [comment]
I have another error...

![CleanShot 2024-09-25 at 22 23 10](https://github.com/user-attachments/assets/ecb85d5f-663c-41ef-a585-f8a0f8a4ae99)

The file was played correctly but I got the error

`25 Sep 18:40:01 - [info] ttsultimate: Hailing .MP3, skip tts, filename: Hailing_positive-notification.mp3
Salvelox /data/sonospollyttsstorage/ttsfiles/5765c1aa356213d1073aab3964614ebf.mp3
25 Sep 18:40:17 - [error] ttsultimate: Error SELECTTRACKSync: upnp: statusCode 500 & upnpErrorCode <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>711</errorCode></UPnPError></detail></s:Fault></s:Body></s:Envelope>`

**Comment by Supergiovane** [comment]
Hi
Could you tell me your node version and nodered version?

**Comment by Fernando-Checa** [comment]
Node red 4.0.3
The node is 0.4.0 dev

**Comment by Supergiovane** [comment]
Hi Fernando
the node version is a little strange.
Could you issue a **node -v** command in a terminal window and write the result here? Thanks.

**Comment by Fernando-Checa** [comment]
~$ node -v
v20.17.0

**Comment by Supergiovane** [comment]
Ok, is all up to date.
The SOAP envelope is coming from your hue device. Don't know why, never happened to me.

**Comment by Fernando-Checa** [comment]
What do you mean by hue? I don't have a hue hub

**Comment by Fernando-Checa** [comment]
The node works and the sound plays, so I don't know what the error means

**Comment by Supergiovane** [comment]
Sorry... i mean sonos

**Comment by Supergiovane** [comment]
The sonos is on the latest firmware, right?

**Comment by Fernando-Checa** [comment]
Yes, it's up to date.
I have an ethernet cable connected to the sonos but for some reason was using wifi.
I disabled wifi to see if it makes a difference

**Comment by jasperlanting10** [comment]
Hello, I am having the same issue as @Fernando-Checa. The whole integration works great, but the music (Spotify in this case) is not automatically resumed. My Node Red is upgraded to the latest version, as well as Home Assistant itself. Do you guys have any updates on the potential fix? 

```xml

"ttsultimate: Error SELECTQUEUESync: upnp: statusCode 500 & upnpErrorCode <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><s:Fault><faultcode>s:Client</faultcode><faultstring>UPnPError</faultstring><detail><UPnPError xmlns="urn:schemas-upnp-org:control-1-0"><errorCode>701</errorCode></UPnPError></detail></s:Fault></s:Body></s:Envelope>"

```

**Comment by Supergiovane** [comment]
Hi
No way to resume third party apps, like spotify, apple music and so on, sorry!
