### ISSUE TITLE
Random error

### ISSUE THREAD

**Issue by Fernando-Checa** [Supergiovane/node-red-contrib-tts-ultimate#93]
Hello,

**Describe the bug**
Sometimes after playing a message, I get this kind of error.
![IMG_0579](https://github.com/user-attachments/assets/84508580-a990-4929-b368-66df1eba1d47)

The message plays fine though.

Sometimes it resumes whatever was playing and sometimes I get this error and then it does not resume.
But if  there’s nothing playing, I also get the error randomly.

**Expected behavior**
Not getting errors and resume playback if it was playing previously.

**Screenshots**

**TTS-Ultimate Version**
latest and latest nodered as well

**Are you running node-red behind homematic, docker or anything similar?** 
 in LXC in Proxmox

Using spanish voice?

**Comment by Supergiovane** [comment]
Hi
Depending from what type of music, Sonos was playing, it can happen that the node cannot resume the music queue. 
Unfortunately, i currently cannot do nothing to fix that, because Sonos API is unable to do so. It all depends from the music queue.

**Comment by Fernando-Checa** [comment]
I understand, but sometimes the error is thrown even when no music or stream is playing

**Comment by Supergiovane** [comment]
Hi
are you sure, that some nodes or functions in your flow, doesn't send anything to the TTS Node? Someone seems to send a command to play a specified file, that doesn't exists.

**Comment by Fernando-Checa** [comment]
Just msg.payload and msg.volume.

I’ll send the flow when I get home.

**Comment by Fernando-Checa** [comment]
Here is the flow..
![CleanShot 2024-11-03 at 20 10 39](https://github.com/user-attachments/assets/7b2a35dd-00cd-450a-9587-24f0ab68296e)

and the node's config

![CleanShot 2024-11-03 at 20 11 06](https://github.com/user-attachments/assets/030f723d-aad1-4d81-9531-47a436e3a2f7)

and this is what I send

![CleanShot 2024-11-03 at 20 12 55](https://github.com/user-attachments/assets/f76c181a-cf24-4999-a4dd-c05154524ed8)

**Comment by Supergiovane** [comment]
Hi
i need the flow's code. Please export it and paste it here between the "<>" tags.
From the screenshot, i see multiple Link nodes and a "clock" icon of another node.

**Comment by Fernando-Checa** [comment]
Yes, the clock is a delay and the other link does not affect the flow.

`[
    {
        "id": "9da2d25465538803",
        "type": "ttsultimate",
        "z": "5fe40c35d0228119",
        "name": "",
        "voice": "Lucia#engineType:standard",
        "ssml": false,
        "sonosipaddress": "192.168.1.240",
        "sonosvolume": "25",
        "sonoshailing": "0",
        "config": "74ef82c249e4582b",
        "property": "payload",
        "propertyType": {},
        "rules": [],
        "playertype": "sonos",
        "speakingrate": "1",
        "speakingpitch": "0",
        "unmuteIfMuted": true,
        "elevenlabsStability": "",
        "elevenlabsSimilarity_boost": "",
        "x": 480,
        "y": 1790,
        "wires": [
            [],
            []
        ]
    },
    {
        "id": "240e31e6321d1c73",
        "type": "link in",
        "z": "5fe40c35d0228119",
        "name": "TTS quiet",
        "links": [
            "4250a94ae8f450a2"
        ],
        "x": 265,
        "y": 1790,
        "wires": [
            [
                "95e8a23e0c4135a2",
                "599899feee357b17"
            ]
        ]
    },
    {
        "id": "95e8a23e0c4135a2",
        "type": "link out",
        "z": "5fe40c35d0228119",
        "name": "calcel ramp",
        "mode": "link",
        "links": [
            "329adf67f5639719"
        ],
        "x": 315,
        "y": 1790,
        "wires": []
    },
    {
        "id": "599899feee357b17",
        "type": "delay",
        "z": "5fe40c35d0228119",
        "name": "",
        "pauseType": "delay",
        "timeout": "1",
        "timeoutUnits": "seconds",
        "rate": "1",
        "nbRateUnits": "1",
        "rateUnits": "second",
        "randomFirst": "1",
        "randomLast": "5",
        "randomUnits": "seconds",
        "drop": false,
        "allowrate": false,
        "outputs": 1,
        "x": 365,
        "y": 1790,
        "wires": [
            [
                "9da2d25465538803"
            ]
        ],
        "l": false
    },
    {
        "id": "74ef82c249e4582b",
        "type": "ttsultimate-config",
        "name": "TTS Amazon",
        "noderedipaddress": "192.168.1.152",
        "noderedport": "1980",
        "purgediratrestart": "leave",
        "ttsservice": "polly",
        "TTSRootFolderPath": ""
    }
]`

**Comment by Fernando-Checa** [comment]
Another thing that I noticed is that if I'm listening to a stream (tunein for example) and I play a TTS message, the node resumes my previous playlist instead of the stream.

**Comment by Supergiovane** [comment]
Hi
About the queue (tunein, for example), it's a known limitation of the non-documented Sonos API. No one can fix it.

About other issue: if you're using boolean-logic-ultimate as well, put a status node here inbetween:

<img width="490" alt="Node-RED___Flow_1" src="https://github.com/user-attachments/assets/59c3bbaf-9cdc-4786-8be2-79840a4420a6">

If not, put in a debug node and see the messages coming from that Link Node, whenever the issue occurs.

**Comment by Fernando-Checa** [comment]
Not using booleans here.. I have a debug node and this is what comes in. In this case it did not give ant error, as most times.

![CleanShot 2024-11-04 at 12 06 23](https://github.com/user-attachments/assets/8b9b12ff-4dbd-434c-963b-8a2c72bdeafe)

I use a node to create a snap of the sonos just in case, but it does not help much.

**Comment by Supergiovane** [comment]
Ok, leave it running until it gives the error.

**Comment by Fernando-Checa** [comment]
This is what came through before the error.
There's a lot of stuff in the message but nothing it should concern to TTS. Most of the time it does not affect TTS and does not throw errors

![CleanShot 2024-11-05 at 09 49 50](https://github.com/user-attachments/assets/0d5e9d4e-4f1f-4a00-afcd-5ab7c9547db8)

**Comment by Supergiovane** [comment]
Hi
This is related to the music queue resuming procedure.
Nothing to care about. 
In the upcoming version, these message will be hidden.

**Comment by Fernando-Checa** [comment]
ok .Thanks!
